package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBACT03C.
 * @citation app/cbl/CBACT03C.cbl
 * Paragraphs translated: 0 of 6; rules translated: 4 of 7.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbact03cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("MAIN-ENTRY: DISPLAY of group item CARD-XREF-RECORD is not translated", "1000-XREFFILE-GET-NEXT: READ statements are not translated", "0000-XREFFILE-OPEN: OPEN statements are not translated", "9000-XREFFILE-CLOSE: CLOSE statements are not translated", "9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository", "9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBACT03C-0016", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT03C (IF END-OF-FILE = 'N').", "app/cbl/CBACT03C.cbl:74-77", false, "performs 1000-XREFFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "END-OF-FILE", "END-OF-FILE", "END-OF-FILE"), "untranslated (performs 1000-XREFFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBACT03C-0017", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT03C (IF END-OF-FILE = 'N').", "app/cbl/CBACT03C.cbl:76-79", false, "performs 1000-XREFFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "CARD-XREF-RECORD", "END-OF-FILE"), "untranslated (performs 1000-XREFFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBACT03C-0018", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '00').", "app/cbl/CBACT03C.cbl:93-96", true, null, List.of("CARD-XREF-RECORD", "XREFFILE-STATUS", "APPL-RESULT", "CARD-XREF-RECORD", "XREFFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT03C-0019", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '10').", "app/cbl/CBACT03C.cbl:97-100", true, null, List.of("XREFFILE-STATUS", "APPL-RESULT", "XREFFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT03C-0020", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '00').", "app/cbl/CBACT03C.cbl:120-123", true, null, List.of("XREFFILE-STATUS", "APPL-RESULT", "XREFFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT03C-0021", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '00').", "app/cbl/CBACT03C.cbl:138-141", false, "CLOSE statements are not translated", List.of("XREFFILE-STATUS", "APPL-RESULT", "APPL-RESULT", "XREFFILE-STATUS"), "untranslated (CLOSE statements are not translated)"),
            new RuleInfo("BR-CBACT03C-0022", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT03C (IF IO-STATUS NOT NUMERIC).", "app/cbl/CBACT03C.cbl:161-164", true, null, List.of("IO-STATUS", "IO-STAT1", "IO-STATUS-04"), ""));

    @Override public String programId() { return "CBACT03C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CBACT03C.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBACT03C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBACT03C-0016": rule0(st); return;
            case "BR-CBACT03C-0017": rule1(st); return;
            case "BR-CBACT03C-0018": rule2(st); return;
            case "BR-CBACT03C-0019": rule3(st); return;
            case "BR-CBACT03C-0020": rule4(st); return;
            case "BR-CBACT03C-0021": rule5(st); return;
            case "BR-CBACT03C-0022": rule6(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pM1000XreffileGetNext(st);
            pM0000XreffileOpen(st);
            pM9000XreffileClose(st);
            pM9999AbendProgram(st);
            pM9910DisplayIoStatus(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        throw new NotTranslatedException("MAIN-ENTRY: DISPLAY of group item CARD-XREF-RECORD is not translated");
    }

    /** Paragraph 1000-XREFFILE-GET-NEXT. */
    void pM1000XreffileGetNext(CobolState st) {
        throw new NotTranslatedException("1000-XREFFILE-GET-NEXT: READ statements are not translated");
    }

    /** Paragraph 0000-XREFFILE-OPEN. */
    void pM0000XreffileOpen(CobolState st) {
        throw new NotTranslatedException("0000-XREFFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 9000-XREFFILE-CLOSE. */
    void pM9000XreffileClose(CobolState st) {
        throw new NotTranslatedException("9000-XREFFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9999-ABEND-PROGRAM. */
    void pM9999AbendProgram(CobolState st) {
        throw new NotTranslatedException("9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository");
    }

    /** Paragraph 9910-DISPLAY-IO-STATUS. */
    void pM9910DisplayIoStatus(CobolState st) {
        throw new NotTranslatedException("9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");
    }

    /**
     * Rule BR-CBACT03C-0016 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT03C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT03C.cbl:74-77
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBACT03C-0016 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT03C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-XREFFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT03C-0016: performs 1000-XREFFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBACT03C-0017 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT03C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT03C.cbl:76-79
     */
    void rule1(CobolState st) {
        // Rule condition: BR-CBACT03C-0017 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT03C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-XREFFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT03C-0017: performs 1000-XREFFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBACT03C-0018 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '00').
     * @citation app/cbl/CBACT03C.cbl:93-96
     */
    void rule2(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBACT03C-0019 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '10').
     * @citation app/cbl/CBACT03C.cbl:97-100
     */
    void rule3(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("16"));
    }

    /**
     * Rule BR-CBACT03C-0020 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '00').
     * @citation app/cbl/CBACT03C.cbl:120-123
     */
    void rule4(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBACT03C-0021 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '00').
     * @citation app/cbl/CBACT03C.cbl:138-141
     */
    void rule5(CobolState st) {
        // Rule condition: BR-CBACT03C-0021 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT03C (IF XREFFILE-STATUS = '00').
        // Untranslated reason: CLOSE statements are not translated
        throw new NotTranslatedException("Rule BR-CBACT03C-0021: CLOSE statements are not translated");
    }

    /**
     * Rule BR-CBACT03C-0022 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT03C (IF IO-STATUS NOT NUMERIC).
     * @citation app/cbl/CBACT03C.cbl:161-164
     */
    void rule6(CobolState st) {
        if ((!(st.isNumeric("IO-STATUS")) || (st.cmp(st.str("IO-STAT1"), "9") == 0))) {
            st.move("IO-STATUS-04", st.val("IO-STAT1"));
        }
    }
}
