package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBACT04C.
 * @citation app/cbl/CBACT04C.cbl
 * Paragraphs translated: 2 of 23; rules translated: 4 of 8.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbact04cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("MAIN-ENTRY: DISPLAY of group item TRAN-CAT-BAL-RECORD is not translated", "0000-TCATBALF-OPEN: OPEN statements are not translated", "0100-XREFFILE-OPEN: OPEN statements are not translated", "0200-DISCGRP-OPEN: OPEN statements are not translated", "0300-ACCTFILE-OPEN: OPEN statements are not translated", "0400-TRANFILE-OPEN: OPEN statements are not translated", "1000-TCATBALF-GET-NEXT: READ statements are not translated", "1050-UPDATE-ACCOUNT: REWRITE statements are not translated", "1100-GET-ACCT-DATA: READ statements are not translated", "1110-GET-XREF-DATA: READ statements are not translated", "1200-GET-INTEREST-RATE: READ statements are not translated", "1200-A-GET-DEFAULT-INT-RATE: READ statements are not translated", "1300-B-WRITE-TX: STRING statements are not translated", "9000-TCATBALF-CLOSE: CLOSE statements are not translated", "9100-XREFFILE-CLOSE: CLOSE statements are not translated", "9200-DISCGRP-CLOSE: CLOSE statements are not translated", "9300-ACCTFILE-CLOSE: CLOSE statements are not translated", "9400-TRANFILE-CLOSE: CLOSE statements are not translated", "Z-GET-DB2-FORMAT-TIMESTAMP: expected TO but found 'CURRENT-DATE'", "9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository", "9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBACT04C-0023", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF END-OF-FILE = 'N').", "app/cbl/CBACT04C.cbl:188-191", false, "performs 1000-TCATBALF-GET-NEXT, which is not translated", List.of("END-OF-FILE", "END-OF-FILE", "END-OF-FILE", "END-OF-FILE"), "untranslated (performs 1000-TCATBALF-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBACT04C-0024", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF END-OF-FILE = 'N').", "app/cbl/CBACT04C.cbl:190-193", true, null, List.of("END-OF-FILE", "WS-RECORD-COUNT", "TRAN-CAT-BAL-RECORD", "END-OF-FILE"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT04C-0025", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF TRANCAT-ACCT-ID NOT= WS-LAST-ACCT-NUM).", "app/cbl/CBACT04C.cbl:193-196", false, "DISPLAY of group item TRAN-CAT-BAL-RECORD is not translated", List.of("TRAN-CAT-BAL-RECORD", "TRANCAT-ACCT-ID", "WS-LAST-ACCT-NUM", "WS-FIRST-TIME", "TRANCAT-ACCT-ID", "WS-LAST-ACCT-NUM"), "untranslated (DISPLAY of group item TRAN-CAT-BAL-RECORD is not translated)"),
            new RuleInfo("BR-CBACT04C-0026", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF WS-FIRST-TIME NOT = 'Y').", "app/cbl/CBACT04C.cbl:194-197", false, "performs 1050-UPDATE-ACCOUNT, which is not translated", List.of("TRANCAT-ACCT-ID", "WS-LAST-ACCT-NUM", "WS-FIRST-TIME", "WS-FIRST-TIME"), "untranslated (performs 1050-UPDATE-ACCOUNT, which is not translated)"),
            new RuleInfo("BR-CBACT04C-0027", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF DIS-INT-RATE NOT = 0).", "app/cbl/CBACT04C.cbl:213-216", false, "performs 1200-GET-INTEREST-RATE, which is not translated", List.of("DIS-INT-RATE", "DIS-INT-RATE"), "untranslated (performs 1200-GET-INTEREST-RATE, which is not translated)"),
            new RuleInfo("BR-CBACT04C-0028", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF TCATBALF-STATUS = '00').", "app/cbl/CBACT04C.cbl:236-239", true, null, List.of("TCATBALF-STATUS", "APPL-RESULT", "TCATBALF-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT04C-0029", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF XREFFILE-STATUS = '00').", "app/cbl/CBACT04C.cbl:254-257", true, null, List.of("XREFFILE-STATUS", "APPL-RESULT", "XREFFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT04C-0030", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT04C (IF DISCGRP-STATUS = '00').", "app/cbl/CBACT04C.cbl:272-275", true, null, List.of("DISCGRP-STATUS", "APPL-RESULT", "DISCGRP-STATUS"), "translated procedural statement(s) (1 op(s))"));

    @Override public String programId() { return "CBACT04C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CBACT04C.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBACT04C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBACT04C-0023": rule0(st); return;
            case "BR-CBACT04C-0024": rule1(st); return;
            case "BR-CBACT04C-0025": rule2(st); return;
            case "BR-CBACT04C-0026": rule3(st); return;
            case "BR-CBACT04C-0027": rule4(st); return;
            case "BR-CBACT04C-0028": rule5(st); return;
            case "BR-CBACT04C-0029": rule6(st); return;
            case "BR-CBACT04C-0030": rule7(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pM0000TcatbalfOpen(st);
            pM0100XreffileOpen(st);
            pM0200DiscgrpOpen(st);
            pM0300AcctfileOpen(st);
            pM0400TranfileOpen(st);
            pM1000TcatbalfGetNext(st);
            pM1050UpdateAccount(st);
            pM1100GetAcctData(st);
            pM1110GetXrefData(st);
            pM1200GetInterestRate(st);
            pM1200AGetDefaultIntRate(st);
            pM1300ComputeInterest(st);
            pM1300BWriteTx(st);
            pM1400ComputeFees(st);
            pM9000TcatbalfClose(st);
            pM9100XreffileClose(st);
            pM9200DiscgrpClose(st);
            pM9300AcctfileClose(st);
            pM9400TranfileClose(st);
            pZGetDb2FormatTimestamp(st);
            pM9999AbendProgram(st);
            pM9910DisplayIoStatus(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        throw new NotTranslatedException("MAIN-ENTRY: DISPLAY of group item TRAN-CAT-BAL-RECORD is not translated");
    }

    /** Paragraph 0000-TCATBALF-OPEN. */
    void pM0000TcatbalfOpen(CobolState st) {
        throw new NotTranslatedException("0000-TCATBALF-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0100-XREFFILE-OPEN. */
    void pM0100XreffileOpen(CobolState st) {
        throw new NotTranslatedException("0100-XREFFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0200-DISCGRP-OPEN. */
    void pM0200DiscgrpOpen(CobolState st) {
        throw new NotTranslatedException("0200-DISCGRP-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0300-ACCTFILE-OPEN. */
    void pM0300AcctfileOpen(CobolState st) {
        throw new NotTranslatedException("0300-ACCTFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0400-TRANFILE-OPEN. */
    void pM0400TranfileOpen(CobolState st) {
        throw new NotTranslatedException("0400-TRANFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 1000-TCATBALF-GET-NEXT. */
    void pM1000TcatbalfGetNext(CobolState st) {
        throw new NotTranslatedException("1000-TCATBALF-GET-NEXT: READ statements are not translated");
    }

    /** Paragraph 1050-UPDATE-ACCOUNT. */
    void pM1050UpdateAccount(CobolState st) {
        throw new NotTranslatedException("1050-UPDATE-ACCOUNT: REWRITE statements are not translated");
    }

    /** Paragraph 1100-GET-ACCT-DATA. */
    void pM1100GetAcctData(CobolState st) {
        throw new NotTranslatedException("1100-GET-ACCT-DATA: READ statements are not translated");
    }

    /** Paragraph 1110-GET-XREF-DATA. */
    void pM1110GetXrefData(CobolState st) {
        throw new NotTranslatedException("1110-GET-XREF-DATA: READ statements are not translated");
    }

    /** Paragraph 1200-GET-INTEREST-RATE. */
    void pM1200GetInterestRate(CobolState st) {
        throw new NotTranslatedException("1200-GET-INTEREST-RATE: READ statements are not translated");
    }

    /** Paragraph 1200-A-GET-DEFAULT-INT-RATE. */
    void pM1200AGetDefaultIntRate(CobolState st) {
        throw new NotTranslatedException("1200-A-GET-DEFAULT-INT-RATE: READ statements are not translated");
    }

    /** Paragraph 1300-COMPUTE-INTEREST. */
    void pM1300ComputeInterest(CobolState st) {
        st.setNum("WS-MONTHLY-INT", st.div((st.num("TRAN-CAT-BAL").multiply(st.num("DIS-INT-RATE"))), new BigDecimal("1200")), false);
        st.setNum("WS-TOTAL-INT", st.num("WS-TOTAL-INT").add(st.num("WS-MONTHLY-INT")), false);
        pM1300BWriteTx(st);
        // EXIT
    }

    /** Paragraph 1300-B-WRITE-TX. */
    void pM1300BWriteTx(CobolState st) {
        throw new NotTranslatedException("1300-B-WRITE-TX: STRING statements are not translated");
    }

    /** Paragraph 1400-COMPUTE-FEES. */
    void pM1400ComputeFees(CobolState st) {
        // EXIT
    }

    /** Paragraph 9000-TCATBALF-CLOSE. */
    void pM9000TcatbalfClose(CobolState st) {
        throw new NotTranslatedException("9000-TCATBALF-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9100-XREFFILE-CLOSE. */
    void pM9100XreffileClose(CobolState st) {
        throw new NotTranslatedException("9100-XREFFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9200-DISCGRP-CLOSE. */
    void pM9200DiscgrpClose(CobolState st) {
        throw new NotTranslatedException("9200-DISCGRP-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9300-ACCTFILE-CLOSE. */
    void pM9300AcctfileClose(CobolState st) {
        throw new NotTranslatedException("9300-ACCTFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9400-TRANFILE-CLOSE. */
    void pM9400TranfileClose(CobolState st) {
        throw new NotTranslatedException("9400-TRANFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph Z-GET-DB2-FORMAT-TIMESTAMP. */
    void pZGetDb2FormatTimestamp(CobolState st) {
        throw new NotTranslatedException("Z-GET-DB2-FORMAT-TIMESTAMP: expected TO but found 'CURRENT-DATE'");
    }

    /** Paragraph 9999-ABEND-PROGRAM. */
    void pM9999AbendProgram(CobolState st) {
        throw new NotTranslatedException("9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository");
    }

    /** Paragraph 9910-DISPLAY-IO-STATUS. */
    void pM9910DisplayIoStatus(CobolState st) {
        throw new NotTranslatedException("9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");
    }

    /**
     * Rule BR-CBACT04C-0023 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT04C.cbl:188-191
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBACT04C-0023 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT04C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-TCATBALF-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT04C-0023: performs 1000-TCATBALF-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBACT04C-0024 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT04C.cbl:190-193
     */
    void rule1(CobolState st) {
        st.setNum("WS-RECORD-COUNT", st.num("WS-RECORD-COUNT").add(new BigDecimal("1")), false);
    }

    /**
     * Rule BR-CBACT04C-0025 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF TRANCAT-ACCT-ID NOT= WS-LAST-ACCT-NUM).
     * @citation app/cbl/CBACT04C.cbl:193-196
     */
    void rule2(CobolState st) {
        // Rule condition: BR-CBACT04C-0025 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT04C (IF TRANCAT-ACCT-ID NOT= WS-LAST-ACCT-NUM).
        // Untranslated reason: DISPLAY of group item TRAN-CAT-BAL-RECORD is not translated
        throw new NotTranslatedException("Rule BR-CBACT04C-0025: DISPLAY of group item TRAN-CAT-BAL-RECORD is not translated");
    }

    /**
     * Rule BR-CBACT04C-0026 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF WS-FIRST-TIME NOT = 'Y').
     * @citation app/cbl/CBACT04C.cbl:194-197
     */
    void rule3(CobolState st) {
        // Rule condition: BR-CBACT04C-0026 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT04C (IF WS-FIRST-TIME NOT = 'Y').
        // Untranslated reason: performs 1050-UPDATE-ACCOUNT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT04C-0026: performs 1050-UPDATE-ACCOUNT, which is not translated");
    }

    /**
     * Rule BR-CBACT04C-0027 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF DIS-INT-RATE NOT = 0).
     * @citation app/cbl/CBACT04C.cbl:213-216
     */
    void rule4(CobolState st) {
        // Rule condition: BR-CBACT04C-0027 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT04C (IF DIS-INT-RATE NOT = 0).
        // Untranslated reason: performs 1200-GET-INTEREST-RATE, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT04C-0027: performs 1200-GET-INTEREST-RATE, which is not translated");
    }

    /**
     * Rule BR-CBACT04C-0028 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF TCATBALF-STATUS = '00').
     * @citation app/cbl/CBACT04C.cbl:236-239
     */
    void rule5(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBACT04C-0029 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF XREFFILE-STATUS = '00').
     * @citation app/cbl/CBACT04C.cbl:254-257
     */
    void rule6(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBACT04C-0030 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT04C (IF DISCGRP-STATUS = '00').
     * @citation app/cbl/CBACT04C.cbl:272-275
     */
    void rule7(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }
}
