package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBACT01C.
 * @citation app/cbl/CBACT01C.cbl
 * Paragraphs translated: 2 of 17; rules translated: 4 of 8.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbact01cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("MAIN-ENTRY: DISPLAY of group item ACCOUNT-RECORD is not translated", "1000-ACCTFILE-GET-NEXT: READ statements are not translated", "1300-POPUL-ACCT-RECORD: called program COBDATFT is not in the repository", "1350-WRITE-ACCT-RECORD: WRITE statements are not translated", "1450-WRITE-ARRY-RECORD: WRITE statements are not translated", "1500-POPUL-VBRC-RECORD: DISPLAY of group item VBRC-REC1 is not translated", "1550-WRITE-VB1-RECORD: WRITE statements are not translated", "1575-WRITE-VB2-RECORD: WRITE statements are not translated", "0000-ACCTFILE-OPEN: OPEN statements are not translated", "2000-OUTFILE-OPEN: OPEN statements are not translated", "3000-ARRFILE-OPEN: OPEN statements are not translated", "4000-VBRFILE-OPEN: OPEN statements are not translated", "9000-ACCTFILE-CLOSE: CLOSE statements are not translated", "9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository", "9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBACT01C-0001", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF END-OF-FILE = 'N').", "app/cbl/CBACT01C.cbl:147-150", false, "performs 1000-ACCTFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "END-OF-FILE", "END-OF-FILE", "END-OF-FILE"), "untranslated (performs 1000-ACCTFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBACT01C-0002", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF END-OF-FILE = 'N').", "app/cbl/CBACT01C.cbl:149-152", false, "performs 1000-ACCTFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "ACCOUNT-RECORD", "END-OF-FILE"), "untranslated (performs 1000-ACCTFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBACT01C-0003", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF ACCTFILE-STATUS = '00').", "app/cbl/CBACT01C.cbl:166-169", true, null, List.of("ACCOUNT-RECORD", "ACCTFILE-STATUS", "APPL-RESULT", "ARR-ARRAY-REC", "ACCTFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT01C-0004", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF ACCTFILE-STATUS = '10').", "app/cbl/CBACT01C.cbl:179-182", true, null, List.of("ACCTFILE-STATUS", "APPL-RESULT", "ACCTFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT01C-0005", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF ACCT-CURR-CYC-DEBIT EQUAL TO ZERO).", "app/cbl/CBACT01C.cbl:235-238", true, null, List.of("OUT-ACCT-CURR-CYC-CREDIT", "ACCT-CURR-CYC-CREDIT", "ACCT-CURR-CYC-DEBIT", "OUT-ACCT-CURR-CYC-DEBIT"), ""),
            new RuleInfo("BR-CBACT01C-0006", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF OUTFILE-STATUS NOT = '00' AND OUTFILE-STAT).", "app/cbl/CBACT01C.cbl:244-247", true, null, List.of("OUTFILE-STATUS", "OUTFILE-STATUS", "OUTFILE-STATUS", "OUTFILE-STATUS", "IO-STATUS", "OUTFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT01C-0007", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF ARRYFILE-STATUS NOT = '00').", "app/cbl/CBACT01C.cbl:265-268", false, "comparison of group item ARRYFILE-STATUS is not translated", List.of("ARRYFILE-STATUS", "ARRYFILE-STATUS", "ARRYFILE-STATUS"), "untranslated (comparison of group item ARRYFILE-STATUS is not translated)"),
            new RuleInfo("BR-CBACT01C-0008", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT01C (IF VBRCFILE-STATUS NOT = '00').", "app/cbl/CBACT01C.cbl:291-294", false, "comparison of group item VBRCFILE-STATUS is not translated", List.of("VBRCFILE-STATUS", "VBRCFILE-STATUS", "VBRCFILE-STATUS"), "untranslated (comparison of group item VBRCFILE-STATUS is not translated)"));

    @Override public String programId() { return "CBACT01C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CBACT01C.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBACT01C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBACT01C-0001": rule0(st); return;
            case "BR-CBACT01C-0002": rule1(st); return;
            case "BR-CBACT01C-0003": rule2(st); return;
            case "BR-CBACT01C-0004": rule3(st); return;
            case "BR-CBACT01C-0005": rule4(st); return;
            case "BR-CBACT01C-0006": rule5(st); return;
            case "BR-CBACT01C-0007": rule6(st); return;
            case "BR-CBACT01C-0008": rule7(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pM1000AcctfileGetNext(st);
            pM1100DisplayAcctRecord(st);
            pM1300PopulAcctRecord(st);
            pM1350WriteAcctRecord(st);
            pM1400PopulArrayRecord(st);
            pM1450WriteArryRecord(st);
            pM1500PopulVbrcRecord(st);
            pM1550WriteVb1Record(st);
            pM1575WriteVb2Record(st);
            pM0000AcctfileOpen(st);
            pM2000OutfileOpen(st);
            pM3000ArrfileOpen(st);
            pM4000VbrfileOpen(st);
            pM9000AcctfileClose(st);
            pM9999AbendProgram(st);
            pM9910DisplayIoStatus(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        throw new NotTranslatedException("MAIN-ENTRY: DISPLAY of group item ACCOUNT-RECORD is not translated");
    }

    /** Paragraph 1000-ACCTFILE-GET-NEXT. */
    void pM1000AcctfileGetNext(CobolState st) {
        throw new NotTranslatedException("1000-ACCTFILE-GET-NEXT: READ statements are not translated");
    }

    /** Paragraph 1100-DISPLAY-ACCT-RECORD. */
    void pM1100DisplayAcctRecord(CobolState st) {
        st.display("ACCT-ID                 :", st.str("ACCT-ID"));
        st.display("ACCT-ACTIVE-STATUS      :", st.str("ACCT-ACTIVE-STATUS"));
        st.display("ACCT-CURR-BAL           :", st.str("ACCT-CURR-BAL"));
        st.display("ACCT-CREDIT-LIMIT       :", st.str("ACCT-CREDIT-LIMIT"));
        st.display("ACCT-CASH-CREDIT-LIMIT  :", st.str("ACCT-CASH-CREDIT-LIMIT"));
        st.display("ACCT-OPEN-DATE          :", st.str("ACCT-OPEN-DATE"));
        st.display("ACCT-EXPIRAION-DATE     :", st.str("ACCT-EXPIRAION-DATE"));
        st.display("ACCT-REISSUE-DATE       :", st.str("ACCT-REISSUE-DATE"));
        st.display("ACCT-CURR-CYC-CREDIT    :", st.str("ACCT-CURR-CYC-CREDIT"));
        st.display("ACCT-CURR-CYC-DEBIT     :", st.str("ACCT-CURR-CYC-DEBIT"));
        st.display("ACCT-GROUP-ID           :", st.str("ACCT-GROUP-ID"));
        st.display("-------------------------------------------------");
        // EXIT
    }

    /** Paragraph 1300-POPUL-ACCT-RECORD. */
    void pM1300PopulAcctRecord(CobolState st) {
        throw new NotTranslatedException("1300-POPUL-ACCT-RECORD: called program COBDATFT is not in the repository");
    }

    /** Paragraph 1350-WRITE-ACCT-RECORD. */
    void pM1350WriteAcctRecord(CobolState st) {
        throw new NotTranslatedException("1350-WRITE-ACCT-RECORD: WRITE statements are not translated");
    }

    /** Paragraph 1400-POPUL-ARRAY-RECORD. */
    void pM1400PopulArrayRecord(CobolState st) {
        st.setNum("ARR-ACCT-ID", st.num("ACCT-ID"), false);
        st.setNum("ARR-ACCT-CURR-BAL", st.num("ACCT-CURR-BAL"), false);
        st.move("ARR-ACCT-CURR-CYC-DEBIT", new BigDecimal("1005.00"));
        st.setNum("ARR-ACCT-CURR-BAL", st.num("ACCT-CURR-BAL"), false);
        st.move("ARR-ACCT-CURR-CYC-DEBIT", new BigDecimal("1525.00"));
        st.move("ARR-ACCT-CURR-BAL", new BigDecimal("-1025.00"));
        st.move("ARR-ACCT-CURR-CYC-DEBIT", new BigDecimal("-2500.00"));
        // EXIT
    }

    /** Paragraph 1450-WRITE-ARRY-RECORD. */
    void pM1450WriteArryRecord(CobolState st) {
        throw new NotTranslatedException("1450-WRITE-ARRY-RECORD: WRITE statements are not translated");
    }

    /** Paragraph 1500-POPUL-VBRC-RECORD. */
    void pM1500PopulVbrcRecord(CobolState st) {
        throw new NotTranslatedException("1500-POPUL-VBRC-RECORD: DISPLAY of group item VBRC-REC1 is not translated");
    }

    /** Paragraph 1550-WRITE-VB1-RECORD. */
    void pM1550WriteVb1Record(CobolState st) {
        throw new NotTranslatedException("1550-WRITE-VB1-RECORD: WRITE statements are not translated");
    }

    /** Paragraph 1575-WRITE-VB2-RECORD. */
    void pM1575WriteVb2Record(CobolState st) {
        throw new NotTranslatedException("1575-WRITE-VB2-RECORD: WRITE statements are not translated");
    }

    /** Paragraph 0000-ACCTFILE-OPEN. */
    void pM0000AcctfileOpen(CobolState st) {
        throw new NotTranslatedException("0000-ACCTFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 2000-OUTFILE-OPEN. */
    void pM2000OutfileOpen(CobolState st) {
        throw new NotTranslatedException("2000-OUTFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 3000-ARRFILE-OPEN. */
    void pM3000ArrfileOpen(CobolState st) {
        throw new NotTranslatedException("3000-ARRFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 4000-VBRFILE-OPEN. */
    void pM4000VbrfileOpen(CobolState st) {
        throw new NotTranslatedException("4000-VBRFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 9000-ACCTFILE-CLOSE. */
    void pM9000AcctfileClose(CobolState st) {
        throw new NotTranslatedException("9000-ACCTFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9999-ABEND-PROGRAM. */
    void pM9999AbendProgram(CobolState st) {
        throw new NotTranslatedException("9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository");
    }

    /** Paragraph 9910-DISPLAY-IO-STATUS. */
    void pM9910DisplayIoStatus(CobolState st) {
        throw new NotTranslatedException("9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");
    }

    /**
     * Rule BR-CBACT01C-0001 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT01C.cbl:147-150
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBACT01C-0001 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT01C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-ACCTFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT01C-0001: performs 1000-ACCTFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBACT01C-0002 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT01C.cbl:149-152
     */
    void rule1(CobolState st) {
        // Rule condition: BR-CBACT01C-0002 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT01C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-ACCTFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT01C-0002: performs 1000-ACCTFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBACT01C-0003 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF ACCTFILE-STATUS = '00').
     * @citation app/cbl/CBACT01C.cbl:166-169
     */
    void rule2(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBACT01C-0004 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF ACCTFILE-STATUS = '10').
     * @citation app/cbl/CBACT01C.cbl:179-182
     */
    void rule3(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("16"));
    }

    /**
     * Rule BR-CBACT01C-0005 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF ACCT-CURR-CYC-DEBIT EQUAL TO ZERO).
     * @citation app/cbl/CBACT01C.cbl:235-238
     */
    void rule4(CobolState st) {
        st.setNum("OUT-ACCT-CURR-CYC-CREDIT", st.num("ACCT-CURR-CYC-CREDIT"), false);
        if ((st.cmp(st.num("ACCT-CURR-CYC-DEBIT"), CobolState.ZEROS) == 0)) {
            st.move("OUT-ACCT-CURR-CYC-DEBIT", new BigDecimal("2525.00"));
        }
    }

    /**
     * Rule BR-CBACT01C-0006 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF OUTFILE-STATUS NOT = '00' AND OUTFILE-STAT).
     * @citation app/cbl/CBACT01C.cbl:244-247
     */
    void rule5(CobolState st) {
        st.move("IO-STATUS", st.val("OUTFILE-STATUS"));
    }

    /**
     * Rule BR-CBACT01C-0007 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF ARRYFILE-STATUS NOT = '00').
     * @citation app/cbl/CBACT01C.cbl:265-268
     */
    void rule6(CobolState st) {
        // Rule condition: BR-CBACT01C-0007 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT01C (IF ARRYFILE-STATUS NOT = '00').
        // Untranslated reason: comparison of group item ARRYFILE-STATUS is not translated
        throw new NotTranslatedException("Rule BR-CBACT01C-0007: comparison of group item ARRYFILE-STATUS is not translated");
    }

    /**
     * Rule BR-CBACT01C-0008 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT01C (IF VBRCFILE-STATUS NOT = '00').
     * @citation app/cbl/CBACT01C.cbl:291-294
     */
    void rule7(CobolState st) {
        // Rule condition: BR-CBACT01C-0008 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT01C (IF VBRCFILE-STATUS NOT = '00').
        // Untranslated reason: comparison of group item VBRCFILE-STATUS is not translated
        throw new NotTranslatedException("Rule BR-CBACT01C-0008: comparison of group item VBRCFILE-STATUS is not translated");
    }
}
