package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBACT02C.
 * @citation app/cbl/CBACT02C.cbl
 * Paragraphs translated: 1 of 6; rules translated: 4 of 7.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbact02cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("MAIN-ENTRY: DISPLAY of group item CARD-RECORD is not translated", "1000-CARDFILE-GET-NEXT: comparison of group item CARDFILE-STATUS is not translated", "0000-CARDFILE-OPEN: comparison of group item CARDFILE-STATUS is not translated", "9000-CARDFILE-CLOSE: comparison of group item CARDFILE-STATUS is not translated", "9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBACT02C-0009", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT02C (IF END-OF-FILE = 'N').", "app/cbl/CBACT02C.cbl:74-77", false, "performs 1000-CARDFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "END-OF-FILE", "END-OF-FILE", "END-OF-FILE"), "untranslated (performs 1000-CARDFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBACT02C-0010", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT02C (IF END-OF-FILE = 'N').", "app/cbl/CBACT02C.cbl:76-79", false, "performs 1000-CARDFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "CARD-RECORD", "END-OF-FILE"), "untranslated (performs 1000-CARDFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBACT02C-0011", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '00').", "app/cbl/CBACT02C.cbl:93-96", true, null, List.of("CARDFILE-FILE", "CARD-RECORD", "CARDFILE-STATUS", "APPL-RESULT", "CARDFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT02C-0012", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '10').", "app/cbl/CBACT02C.cbl:97-100", true, null, List.of("CARDFILE-STATUS", "APPL-RESULT", "CARDFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT02C-0013", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '00').", "app/cbl/CBACT02C.cbl:120-123", true, null, List.of("CARDFILE-FILE", "CARDFILE-STATUS", "APPL-RESULT", "CARDFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBACT02C-0014", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '00').", "app/cbl/CBACT02C.cbl:138-141", false, "comparison of group item CARDFILE-STATUS is not translated", List.of("CARDFILE-FILE", "CARDFILE-STATUS", "APPL-RESULT", "APPL-RESULT", "CARDFILE-STATUS"), "untranslated (comparison of group item CARDFILE-STATUS is not translated)"),
            new RuleInfo("BR-CBACT02C-0015", "VALIDATION", "Validate field conditions and reject invalid inputs in CBACT02C (IF IO-STATUS NOT NUMERIC).", "app/cbl/CBACT02C.cbl:161-164", true, null, List.of("IO-STATUS", "IO-STAT1", "IO-STATUS-04"), ""));

    @Override public String programId() { return "CBACT02C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CBACT02C.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBACT02C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBACT02C-0009": rule0(st); return;
            case "BR-CBACT02C-0010": rule1(st); return;
            case "BR-CBACT02C-0011": rule2(st); return;
            case "BR-CBACT02C-0012": rule3(st); return;
            case "BR-CBACT02C-0013": rule4(st); return;
            case "BR-CBACT02C-0014": rule5(st); return;
            case "BR-CBACT02C-0015": rule6(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pM1000CardfileGetNext(st);
            pM0000CardfileOpen(st);
            pM9000CardfileClose(st);
            pM9999AbendProgram(st);
            pM9910DisplayIoStatus(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        throw new NotTranslatedException("MAIN-ENTRY: DISPLAY of group item CARD-RECORD is not translated");
    }

    /** Paragraph 1000-CARDFILE-GET-NEXT. */
    void pM1000CardfileGetNext(CobolState st) {
        throw new NotTranslatedException("1000-CARDFILE-GET-NEXT: comparison of group item CARDFILE-STATUS is not translated");
    }

    /** Paragraph 0000-CARDFILE-OPEN. */
    void pM0000CardfileOpen(CobolState st) {
        throw new NotTranslatedException("0000-CARDFILE-OPEN: comparison of group item CARDFILE-STATUS is not translated");
    }

    /** Paragraph 9000-CARDFILE-CLOSE. */
    void pM9000CardfileClose(CobolState st) {
        throw new NotTranslatedException("9000-CARDFILE-CLOSE: comparison of group item CARDFILE-STATUS is not translated");
    }

    /** Paragraph 9999-ABEND-PROGRAM. */
    void pM9999AbendProgram(CobolState st) {
        st.display("ABENDING PROGRAM");
        st.move("TIMING", new BigDecimal("0"));
        st.move("ABCODE", new BigDecimal("999"));
        registry.call("CEE3ABD", st, new String[]{"ABCODE", "TIMING"}, new boolean[]{true, true});
    }

    /** Paragraph 9910-DISPLAY-IO-STATUS. */
    void pM9910DisplayIoStatus(CobolState st) {
        throw new NotTranslatedException("9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");
    }

    /**
     * Rule BR-CBACT02C-0009 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT02C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT02C.cbl:74-77
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBACT02C-0009 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT02C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-CARDFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT02C-0009: performs 1000-CARDFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBACT02C-0010 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT02C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBACT02C.cbl:76-79
     */
    void rule1(CobolState st) {
        // Rule condition: BR-CBACT02C-0010 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT02C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-CARDFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBACT02C-0010: performs 1000-CARDFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBACT02C-0011 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '00').
     * @citation app/cbl/CBACT02C.cbl:93-96
     */
    void rule2(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBACT02C-0012 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '10').
     * @citation app/cbl/CBACT02C.cbl:97-100
     */
    void rule3(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("16"));
    }

    /**
     * Rule BR-CBACT02C-0013 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '00').
     * @citation app/cbl/CBACT02C.cbl:120-123
     */
    void rule4(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBACT02C-0014 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '00').
     * @citation app/cbl/CBACT02C.cbl:138-141
     */
    void rule5(CobolState st) {
        // Rule condition: BR-CBACT02C-0014 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBACT02C (IF CARDFILE-STATUS = '00').
        // Untranslated reason: comparison of group item CARDFILE-STATUS is not translated
        throw new NotTranslatedException("Rule BR-CBACT02C-0014: comparison of group item CARDFILE-STATUS is not translated");
    }

    /**
     * Rule BR-CBACT02C-0015 (VALIDATION): Validate field conditions and reject invalid inputs in CBACT02C (IF IO-STATUS NOT NUMERIC).
     * @citation app/cbl/CBACT02C.cbl:161-164
     */
    void rule6(CobolState st) {
        if ((!(st.isNumeric("IO-STATUS")) || (st.cmp(st.str("IO-STAT1"), "9") == 0))) {
            st.move("IO-STATUS-04", st.val("IO-STAT1"));
        }
    }
}
