package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBCUS01C.
 * @citation app/cbl/CBCUS01C.cbl
 * Paragraphs translated: 0 of 6; rules translated: 4 of 7.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbcus01cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("MAIN-ENTRY: DISPLAY of group item CUSTOMER-RECORD is not translated", "1000-CUSTFILE-GET-NEXT: READ statements are not translated", "0000-CUSTFILE-OPEN: OPEN statements are not translated", "9000-CUSTFILE-CLOSE: CLOSE statements are not translated", "Z-ABEND-PROGRAM: called program CEE3ABD is not in the repository", "Z-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBCUS01C-0031", "VALIDATION", "Validate field conditions and reject invalid inputs in CBCUS01C (IF END-OF-FILE = 'N').", "app/cbl/CBCUS01C.cbl:74-77", false, "performs 1000-CUSTFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "END-OF-FILE", "END-OF-FILE", "END-OF-FILE"), "untranslated (performs 1000-CUSTFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBCUS01C-0032", "VALIDATION", "Validate field conditions and reject invalid inputs in CBCUS01C (IF END-OF-FILE = 'N').", "app/cbl/CBCUS01C.cbl:76-79", false, "performs 1000-CUSTFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "CUSTOMER-RECORD", "END-OF-FILE"), "untranslated (performs 1000-CUSTFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBCUS01C-0033", "VALIDATION", "Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '00').", "app/cbl/CBCUS01C.cbl:93-96", true, null, List.of("CUSTOMER-RECORD", "CUSTFILE-STATUS", "APPL-RESULT", "CUSTOMER-RECORD", "CUSTFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBCUS01C-0034", "VALIDATION", "Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '10').", "app/cbl/CBCUS01C.cbl:97-100", true, null, List.of("CUSTFILE-STATUS", "APPL-RESULT", "CUSTFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBCUS01C-0035", "VALIDATION", "Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '00').", "app/cbl/CBCUS01C.cbl:120-123", true, null, List.of("CUSTFILE-STATUS", "APPL-RESULT", "CUSTFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBCUS01C-0036", "VALIDATION", "Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '00').", "app/cbl/CBCUS01C.cbl:138-141", false, "CLOSE statements are not translated", List.of("CUSTFILE-STATUS", "APPL-RESULT", "APPL-RESULT", "CUSTFILE-STATUS"), "untranslated (CLOSE statements are not translated)"),
            new RuleInfo("BR-CBCUS01C-0037", "VALIDATION", "Validate field conditions and reject invalid inputs in CBCUS01C (IF IO-STATUS NOT NUMERIC).", "app/cbl/CBCUS01C.cbl:161-164", true, null, List.of("IO-STATUS", "IO-STAT1", "IO-STATUS-04"), ""));

    @Override public String programId() { return "CBCUS01C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CBCUS01C.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBCUS01C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBCUS01C-0031": rule0(st); return;
            case "BR-CBCUS01C-0032": rule1(st); return;
            case "BR-CBCUS01C-0033": rule2(st); return;
            case "BR-CBCUS01C-0034": rule3(st); return;
            case "BR-CBCUS01C-0035": rule4(st); return;
            case "BR-CBCUS01C-0036": rule5(st); return;
            case "BR-CBCUS01C-0037": rule6(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pM1000CustfileGetNext(st);
            pM0000CustfileOpen(st);
            pM9000CustfileClose(st);
            pZAbendProgram(st);
            pZDisplayIoStatus(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        throw new NotTranslatedException("MAIN-ENTRY: DISPLAY of group item CUSTOMER-RECORD is not translated");
    }

    /** Paragraph 1000-CUSTFILE-GET-NEXT. */
    void pM1000CustfileGetNext(CobolState st) {
        throw new NotTranslatedException("1000-CUSTFILE-GET-NEXT: READ statements are not translated");
    }

    /** Paragraph 0000-CUSTFILE-OPEN. */
    void pM0000CustfileOpen(CobolState st) {
        throw new NotTranslatedException("0000-CUSTFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 9000-CUSTFILE-CLOSE. */
    void pM9000CustfileClose(CobolState st) {
        throw new NotTranslatedException("9000-CUSTFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph Z-ABEND-PROGRAM. */
    void pZAbendProgram(CobolState st) {
        throw new NotTranslatedException("Z-ABEND-PROGRAM: called program CEE3ABD is not in the repository");
    }

    /** Paragraph Z-DISPLAY-IO-STATUS. */
    void pZDisplayIoStatus(CobolState st) {
        throw new NotTranslatedException("Z-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");
    }

    /**
     * Rule BR-CBCUS01C-0031 (VALIDATION): Validate field conditions and reject invalid inputs in CBCUS01C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBCUS01C.cbl:74-77
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBCUS01C-0031 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBCUS01C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-CUSTFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBCUS01C-0031: performs 1000-CUSTFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBCUS01C-0032 (VALIDATION): Validate field conditions and reject invalid inputs in CBCUS01C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBCUS01C.cbl:76-79
     */
    void rule1(CobolState st) {
        // Rule condition: BR-CBCUS01C-0032 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBCUS01C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-CUSTFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBCUS01C-0032: performs 1000-CUSTFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBCUS01C-0033 (VALIDATION): Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '00').
     * @citation app/cbl/CBCUS01C.cbl:93-96
     */
    void rule2(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBCUS01C-0034 (VALIDATION): Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '10').
     * @citation app/cbl/CBCUS01C.cbl:97-100
     */
    void rule3(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("16"));
    }

    /**
     * Rule BR-CBCUS01C-0035 (VALIDATION): Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '00').
     * @citation app/cbl/CBCUS01C.cbl:120-123
     */
    void rule4(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBCUS01C-0036 (VALIDATION): Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '00').
     * @citation app/cbl/CBCUS01C.cbl:138-141
     */
    void rule5(CobolState st) {
        // Rule condition: BR-CBCUS01C-0036 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBCUS01C (IF CUSTFILE-STATUS = '00').
        // Untranslated reason: CLOSE statements are not translated
        throw new NotTranslatedException("Rule BR-CBCUS01C-0036: CLOSE statements are not translated");
    }

    /**
     * Rule BR-CBCUS01C-0037 (VALIDATION): Validate field conditions and reject invalid inputs in CBCUS01C (IF IO-STATUS NOT NUMERIC).
     * @citation app/cbl/CBCUS01C.cbl:161-164
     */
    void rule6(CobolState st) {
        if ((!(st.isNumeric("IO-STATUS")) || (st.cmp(st.str("IO-STAT1"), "9") == 0))) {
            st.move("IO-STATUS-04", st.val("IO-STAT1"));
        }
    }
}
