package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBTRN02C.
 * @citation app/cbl/CBTRN02C.cbl
 * Paragraphs translated: 7 of 27; rules translated: 7 of 8.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbtrn02cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("0000-DALYTRAN-OPEN: comparison of group item DALYTRAN-STATUS is not translated", "0100-TRANFILE-OPEN: comparison of group item TRANFILE-STATUS is not translated", "0200-XREFFILE-OPEN: comparison of group item XREFFILE-STATUS is not translated", "0300-DALYREJS-OPEN: comparison of group item DALYREJS-STATUS is not translated", "0400-ACCTFILE-OPEN: comparison of group item ACCTFILE-STATUS is not translated", "0500-TCATBALF-OPEN: comparison of group item TCATBALF-STATUS is not translated", "1000-DALYTRAN-GET-NEXT: comparison of group item DALYTRAN-STATUS is not translated", "2500-WRITE-REJECT-REC: comparison of group item DALYREJS-STATUS is not translated", "2700-UPDATE-TCATBAL: DISPLAY of group item FD-TRAN-CAT-KEY is not translated", "2700-A-CREATE-TCATBAL-REC: comparison of group item TCATBALF-STATUS is not translated", "2700-B-UPDATE-TCATBAL-REC: comparison of group item TCATBALF-STATUS is not translated", "2900-WRITE-TRANSACTION-FILE: comparison of group item TRANFILE-STATUS is not translated", "9000-DALYTRAN-CLOSE: comparison of group item DALYTRAN-STATUS is not translated", "9100-TRANFILE-CLOSE: comparison of group item TRANFILE-STATUS is not translated", "9200-XREFFILE-CLOSE: comparison of group item XREFFILE-STATUS is not translated", "9300-DALYREJS-CLOSE: comparison of group item DALYREJS-STATUS is not translated", "9400-ACCTFILE-CLOSE: comparison of group item ACCTFILE-STATUS is not translated", "9500-TCATBALF-CLOSE: comparison of group item TCATBALF-STATUS is not translated", "Z-GET-DB2-FORMAT-TIMESTAMP: expected TO but found 'CURRENT-DATE'", "9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBTRN02C-0051", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF END-OF-FILE = 'N').", "app/cbl/CBTRN02C.cbl:202-205", false, "performs 1000-DALYTRAN-GET-NEXT, which is not translated", List.of("END-OF-FILE", "END-OF-FILE", "END-OF-FILE", "END-OF-FILE"), "untranslated (performs 1000-DALYTRAN-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBTRN02C-0052", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF END-OF-FILE = 'N').", "app/cbl/CBTRN02C.cbl:204-207", true, null, List.of("END-OF-FILE", "WS-TRANSACTION-COUNT", "END-OF-FILE"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBTRN02C-0053", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF WS-VALIDATION-FAIL-REASON = 0).", "app/cbl/CBTRN02C.cbl:210-213", true, null, List.of("WS-VALIDATION-FAIL-REASON"), ""),
            new RuleInfo("BR-CBTRN02C-0054", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF WS-REJECT-COUNT > 0).", "app/cbl/CBTRN02C.cbl:228-231", true, null, List.of("WS-REJECT-COUNT", "RETURN-CODE"), ""),
            new RuleInfo("BR-CBTRN02C-0055", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF DALYTRAN-STATUS = '00').", "app/cbl/CBTRN02C.cbl:238-241", true, null, List.of("DALYTRAN-FILE", "DALYTRAN-STATUS", "APPL-RESULT", "DALYTRAN-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBTRN02C-0056", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF TRANFILE-STATUS = '00').", "app/cbl/CBTRN02C.cbl:256-259", true, null, List.of("TRANSACT-FILE", "TRANFILE-STATUS", "APPL-RESULT", "TRANFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBTRN02C-0057", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF XREFFILE-STATUS = '00').", "app/cbl/CBTRN02C.cbl:275-278", true, null, List.of("XREF-FILE", "XREFFILE-STATUS", "APPL-RESULT", "XREFFILE-STATUS"), "translated procedural statement(s) (1 op(s))"),
            new RuleInfo("BR-CBTRN02C-0058", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN02C (IF DALYREJS-STATUS = '00').", "app/cbl/CBTRN02C.cbl:293-296", true, null, List.of("DALYREJS-FILE", "DALYREJS-STATUS", "APPL-RESULT", "DALYREJS-STATUS"), "translated procedural statement(s) (1 op(s))"));

    @Override public String programId() { return "CBTRN02C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CBTRN02C.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBTRN02C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBTRN02C-0051": rule0(st); return;
            case "BR-CBTRN02C-0052": rule1(st); return;
            case "BR-CBTRN02C-0053": rule2(st); return;
            case "BR-CBTRN02C-0054": rule3(st); return;
            case "BR-CBTRN02C-0055": rule4(st); return;
            case "BR-CBTRN02C-0056": rule5(st); return;
            case "BR-CBTRN02C-0057": rule6(st); return;
            case "BR-CBTRN02C-0058": rule7(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pM0000DalytranOpen(st);
            pM0100TranfileOpen(st);
            pM0200XreffileOpen(st);
            pM0300DalyrejsOpen(st);
            pM0400AcctfileOpen(st);
            pM0500TcatbalfOpen(st);
            pM1000DalytranGetNext(st);
            pM1500ValidateTran(st);
            pM1500ALookupXref(st);
            pM1500BLookupAcct(st);
            pM2000PostTransaction(st);
            pM2500WriteRejectRec(st);
            pM2700UpdateTcatbal(st);
            pM2700ACreateTcatbalRec(st);
            pM2700BUpdateTcatbalRec(st);
            pM2800UpdateAccountRec(st);
            pM2900WriteTransactionFile(st);
            pM9000DalytranClose(st);
            pM9100TranfileClose(st);
            pM9200XreffileClose(st);
            pM9300DalyrejsClose(st);
            pM9400AcctfileClose(st);
            pM9500TcatbalfClose(st);
            pZGetDb2FormatTimestamp(st);
            pM9999AbendProgram(st);
            pM9910DisplayIoStatus(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        st.display("START OF EXECUTION OF PROGRAM CBTRN02C");
        pM0000DalytranOpen(st);
        pM0100TranfileOpen(st);
        pM0200XreffileOpen(st);
        pM0300DalyrejsOpen(st);
        pM0400AcctfileOpen(st);
        pM0500TcatbalfOpen(st);
        while (!(st.cmp(st.str("END-OF-FILE"), "Y") == 0)) {
            st.tick();
            if ((st.cmp(st.str("END-OF-FILE"), "N") == 0)) {
                pM1000DalytranGetNext(st);
                if ((st.cmp(st.str("END-OF-FILE"), "N") == 0)) {
                    st.setNum("WS-TRANSACTION-COUNT", st.num("WS-TRANSACTION-COUNT").add(new BigDecimal("1")), false);
                    st.move("WS-VALIDATION-FAIL-REASON", new BigDecimal("0"));
                    st.move("WS-VALIDATION-FAIL-REASON-DESC", CobolState.SPACES);
                    pM1500ValidateTran(st);
                    if ((st.cmp(st.num("WS-VALIDATION-FAIL-REASON"), new BigDecimal("0")) == 0)) {
                        pM2000PostTransaction(st);
                    } else {
                        st.setNum("WS-REJECT-COUNT", st.num("WS-REJECT-COUNT").add(new BigDecimal("1")), false);
                        pM2500WriteRejectRec(st);
                    }
                }
            }
        }
        pM9000DalytranClose(st);
        pM9100TranfileClose(st);
        pM9200XreffileClose(st);
        pM9300DalyrejsClose(st);
        pM9400AcctfileClose(st);
        pM9500TcatbalfClose(st);
        st.display("TRANSACTIONS PROCESSED :", st.str("WS-TRANSACTION-COUNT"));
        st.display("TRANSACTIONS REJECTED  :", st.str("WS-REJECT-COUNT"));
        if ((st.cmp(st.num("WS-REJECT-COUNT"), new BigDecimal("0")) > 0)) {
            st.move("RETURN-CODE", new BigDecimal("4"));
        }
        st.display("END OF EXECUTION OF PROGRAM CBTRN02C");
        st.exitProgram();
    }

    /** Paragraph 0000-DALYTRAN-OPEN. */
    void pM0000DalytranOpen(CobolState st) {
        throw new NotTranslatedException("0000-DALYTRAN-OPEN: comparison of group item DALYTRAN-STATUS is not translated");
    }

    /** Paragraph 0100-TRANFILE-OPEN. */
    void pM0100TranfileOpen(CobolState st) {
        throw new NotTranslatedException("0100-TRANFILE-OPEN: comparison of group item TRANFILE-STATUS is not translated");
    }

    /** Paragraph 0200-XREFFILE-OPEN. */
    void pM0200XreffileOpen(CobolState st) {
        throw new NotTranslatedException("0200-XREFFILE-OPEN: comparison of group item XREFFILE-STATUS is not translated");
    }

    /** Paragraph 0300-DALYREJS-OPEN. */
    void pM0300DalyrejsOpen(CobolState st) {
        throw new NotTranslatedException("0300-DALYREJS-OPEN: comparison of group item DALYREJS-STATUS is not translated");
    }

    /** Paragraph 0400-ACCTFILE-OPEN. */
    void pM0400AcctfileOpen(CobolState st) {
        throw new NotTranslatedException("0400-ACCTFILE-OPEN: comparison of group item ACCTFILE-STATUS is not translated");
    }

    /** Paragraph 0500-TCATBALF-OPEN. */
    void pM0500TcatbalfOpen(CobolState st) {
        throw new NotTranslatedException("0500-TCATBALF-OPEN: comparison of group item TCATBALF-STATUS is not translated");
    }

    /** Paragraph 1000-DALYTRAN-GET-NEXT. */
    void pM1000DalytranGetNext(CobolState st) {
        throw new NotTranslatedException("1000-DALYTRAN-GET-NEXT: comparison of group item DALYTRAN-STATUS is not translated");
    }

    /** Paragraph 1500-VALIDATE-TRAN. */
    void pM1500ValidateTran(CobolState st) {
        pM1500ALookupXref(st);
        if ((st.cmp(st.num("WS-VALIDATION-FAIL-REASON"), new BigDecimal("0")) == 0)) {
            pM1500BLookupAcct(st);
        } else {
            // CONTINUE
        }
        // EXIT
    }

    /** Paragraph 1500-A-LOOKUP-XREF. */
    void pM1500ALookupXref(CobolState st) {
        st.move("FD-XREF-CARD-NUM", st.val("DALYTRAN-CARD-NUM"));
        if (!st.readFile("XREF-FILE", "CARD-XREF-RECORD")) {
            st.move("WS-VALIDATION-FAIL-REASON", new BigDecimal("100"));
            st.move("WS-VALIDATION-FAIL-REASON-DESC", "INVALID CARD NUMBER FOUND");
        } else {
            // CONTINUE
        }
        // EXIT
    }

    /** Paragraph 1500-B-LOOKUP-ACCT. */
    void pM1500BLookupAcct(CobolState st) {
        st.setNum("FD-ACCT-ID", st.num("XREF-ACCT-ID"), false);
        if (!st.readFile("ACCOUNT-FILE", "ACCOUNT-RECORD")) {
            st.move("WS-VALIDATION-FAIL-REASON", new BigDecimal("101"));
            st.move("WS-VALIDATION-FAIL-REASON-DESC", "ACCOUNT RECORD NOT FOUND");
        } else {
            st.setNum("WS-TEMP-BAL", st.num("ACCT-CURR-CYC-CREDIT").subtract(st.num("ACCT-CURR-CYC-DEBIT")).add(st.num("DALYTRAN-AMT")), false);
            if ((st.cmp(st.num("ACCT-CREDIT-LIMIT"), st.num("WS-TEMP-BAL")) >= 0)) {
                // CONTINUE
            } else {
                st.move("WS-VALIDATION-FAIL-REASON", new BigDecimal("102"));
                st.move("WS-VALIDATION-FAIL-REASON-DESC", "OVERLIMIT TRANSACTION");
            }
            if ((st.cmp(st.str("ACCT-EXPIRAION-DATE"), st.str("DALYTRAN-ORIG-TS")) >= 0)) {
                // CONTINUE
            } else {
                st.move("WS-VALIDATION-FAIL-REASON", new BigDecimal("103"));
                st.move("WS-VALIDATION-FAIL-REASON-DESC", "TRANSACTION RECEIVED AFTER ACCT EXPIRATION");
            }
        }
        // EXIT
    }

    /** Paragraph 2000-POST-TRANSACTION. */
    void pM2000PostTransaction(CobolState st) {
        st.move("TRAN-ID", st.val("DALYTRAN-ID"));
        st.move("TRAN-TYPE-CD", st.val("DALYTRAN-TYPE-CD"));
        st.setNum("TRAN-CAT-CD", st.num("DALYTRAN-CAT-CD"), false);
        st.move("TRAN-SOURCE", st.val("DALYTRAN-SOURCE"));
        st.move("TRAN-DESC", st.val("DALYTRAN-DESC"));
        st.setNum("TRAN-AMT", st.num("DALYTRAN-AMT"), false);
        st.setNum("TRAN-MERCHANT-ID", st.num("DALYTRAN-MERCHANT-ID"), false);
        st.move("TRAN-MERCHANT-NAME", st.val("DALYTRAN-MERCHANT-NAME"));
        st.move("TRAN-MERCHANT-CITY", st.val("DALYTRAN-MERCHANT-CITY"));
        st.move("TRAN-MERCHANT-ZIP", st.val("DALYTRAN-MERCHANT-ZIP"));
        st.move("TRAN-CARD-NUM", st.val("DALYTRAN-CARD-NUM"));
        st.move("TRAN-ORIG-TS", st.val("DALYTRAN-ORIG-TS"));
        pZGetDb2FormatTimestamp(st);
        st.move("TRAN-PROC-TS", st.val("DB2-FORMAT-TS"));
        pM2700UpdateTcatbal(st);
        pM2800UpdateAccountRec(st);
        pM2900WriteTransactionFile(st);
        // EXIT
    }

    /** Paragraph 2500-WRITE-REJECT-REC. */
    void pM2500WriteRejectRec(CobolState st) {
        throw new NotTranslatedException("2500-WRITE-REJECT-REC: comparison of group item DALYREJS-STATUS is not translated");
    }

    /** Paragraph 2700-UPDATE-TCATBAL. */
    void pM2700UpdateTcatbal(CobolState st) {
        throw new NotTranslatedException("2700-UPDATE-TCATBAL: DISPLAY of group item FD-TRAN-CAT-KEY is not translated");
    }

    /** Paragraph 2700-A-CREATE-TCATBAL-REC. */
    void pM2700ACreateTcatbalRec(CobolState st) {
        throw new NotTranslatedException("2700-A-CREATE-TCATBAL-REC: comparison of group item TCATBALF-STATUS is not translated");
    }

    /** Paragraph 2700-B-UPDATE-TCATBAL-REC. */
    void pM2700BUpdateTcatbalRec(CobolState st) {
        throw new NotTranslatedException("2700-B-UPDATE-TCATBAL-REC: comparison of group item TCATBALF-STATUS is not translated");
    }

    /** Paragraph 2800-UPDATE-ACCOUNT-REC. */
    void pM2800UpdateAccountRec(CobolState st) {
        st.setNum("ACCT-CURR-BAL", st.num("ACCT-CURR-BAL").add(st.num("DALYTRAN-AMT")), false);
        if ((st.cmp(st.num("DALYTRAN-AMT"), new BigDecimal("0")) >= 0)) {
            st.setNum("ACCT-CURR-CYC-CREDIT", st.num("ACCT-CURR-CYC-CREDIT").add(st.num("DALYTRAN-AMT")), false);
        } else {
            st.setNum("ACCT-CURR-CYC-DEBIT", st.num("ACCT-CURR-CYC-DEBIT").add(st.num("DALYTRAN-AMT")), false);
        }
        if (!st.rewriteFile("FD-ACCTFILE-REC", "ACCOUNT-RECORD")) {
            st.move("WS-VALIDATION-FAIL-REASON", new BigDecimal("109"));
            st.move("WS-VALIDATION-FAIL-REASON-DESC", "ACCOUNT RECORD NOT FOUND");
        }
        // EXIT
    }

    /** Paragraph 2900-WRITE-TRANSACTION-FILE. */
    void pM2900WriteTransactionFile(CobolState st) {
        throw new NotTranslatedException("2900-WRITE-TRANSACTION-FILE: comparison of group item TRANFILE-STATUS is not translated");
    }

    /** Paragraph 9000-DALYTRAN-CLOSE. */
    void pM9000DalytranClose(CobolState st) {
        throw new NotTranslatedException("9000-DALYTRAN-CLOSE: comparison of group item DALYTRAN-STATUS is not translated");
    }

    /** Paragraph 9100-TRANFILE-CLOSE. */
    void pM9100TranfileClose(CobolState st) {
        throw new NotTranslatedException("9100-TRANFILE-CLOSE: comparison of group item TRANFILE-STATUS is not translated");
    }

    /** Paragraph 9200-XREFFILE-CLOSE. */
    void pM9200XreffileClose(CobolState st) {
        throw new NotTranslatedException("9200-XREFFILE-CLOSE: comparison of group item XREFFILE-STATUS is not translated");
    }

    /** Paragraph 9300-DALYREJS-CLOSE. */
    void pM9300DalyrejsClose(CobolState st) {
        throw new NotTranslatedException("9300-DALYREJS-CLOSE: comparison of group item DALYREJS-STATUS is not translated");
    }

    /** Paragraph 9400-ACCTFILE-CLOSE. */
    void pM9400AcctfileClose(CobolState st) {
        throw new NotTranslatedException("9400-ACCTFILE-CLOSE: comparison of group item ACCTFILE-STATUS is not translated");
    }

    /** Paragraph 9500-TCATBALF-CLOSE. */
    void pM9500TcatbalfClose(CobolState st) {
        throw new NotTranslatedException("9500-TCATBALF-CLOSE: comparison of group item TCATBALF-STATUS is not translated");
    }

    /** Paragraph Z-GET-DB2-FORMAT-TIMESTAMP. */
    void pZGetDb2FormatTimestamp(CobolState st) {
        throw new NotTranslatedException("Z-GET-DB2-FORMAT-TIMESTAMP: expected TO but found 'CURRENT-DATE'");
    }

    /** Paragraph 9999-ABEND-PROGRAM. */
    void pM9999AbendProgram(CobolState st) {
        st.display("ABENDING PROGRAM");
        st.move("TIMING", new BigDecimal("0"));
        st.move("ABCODE", new BigDecimal("999"));
        registry.call("CEE3ABD", st, new String[]{"ABCODE", "TIMING"}, new boolean[]{true, true});
    }

    /** Paragraph 9910-DISPLAY-IO-STATUS. */
    void pM9910DisplayIoStatus(CobolState st) {
        throw new NotTranslatedException("9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");
    }

    /**
     * Rule BR-CBTRN02C-0051 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBTRN02C.cbl:202-205
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBTRN02C-0051 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN02C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-DALYTRAN-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBTRN02C-0051: performs 1000-DALYTRAN-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBTRN02C-0052 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBTRN02C.cbl:204-207
     */
    void rule1(CobolState st) {
        st.setNum("WS-TRANSACTION-COUNT", st.num("WS-TRANSACTION-COUNT").add(new BigDecimal("1")), false);
    }

    /**
     * Rule BR-CBTRN02C-0053 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF WS-VALIDATION-FAIL-REASON = 0).
     * @citation app/cbl/CBTRN02C.cbl:210-213
     */
    void rule2(CobolState st) {
        pM1500ValidateTran(st);
        if ((st.cmp(st.num("WS-VALIDATION-FAIL-REASON"), new BigDecimal("0")) == 0)) {
            pM2000PostTransaction(st);
        } else {
        }
    }

    /**
     * Rule BR-CBTRN02C-0054 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF WS-REJECT-COUNT > 0).
     * @citation app/cbl/CBTRN02C.cbl:228-231
     */
    void rule3(CobolState st) {
        st.display("TRANSACTIONS REJECTED  :", st.str("WS-REJECT-COUNT"));
        if ((st.cmp(st.num("WS-REJECT-COUNT"), new BigDecimal("0")) > 0)) {
            st.move("RETURN-CODE", new BigDecimal("4"));
        }
    }

    /**
     * Rule BR-CBTRN02C-0055 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF DALYTRAN-STATUS = '00').
     * @citation app/cbl/CBTRN02C.cbl:238-241
     */
    void rule4(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBTRN02C-0056 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF TRANFILE-STATUS = '00').
     * @citation app/cbl/CBTRN02C.cbl:256-259
     */
    void rule5(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBTRN02C-0057 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF XREFFILE-STATUS = '00').
     * @citation app/cbl/CBTRN02C.cbl:275-278
     */
    void rule6(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }

    /**
     * Rule BR-CBTRN02C-0058 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN02C (IF DALYREJS-STATUS = '00').
     * @citation app/cbl/CBTRN02C.cbl:293-296
     */
    void rule7(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }
}
