package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBTRN03C.
 * @citation app/cbl/CBTRN03C.cbl
 * Paragraphs translated: 4 of 27; rules translated: 3 of 8.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbtrn03cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("MAIN-ENTRY: NEXT SENTENCE is not translated", "0550-DATEPARM-READ: READ statements are not translated", "1000-TRANFILE-GET-NEXT: READ statements are not translated", "1100-WRITE-TRANSACTION-REPORT: FUNCTION expressions are not translated", "1111-WRITE-REPORT-REC: WRITE statements are not translated", "1120-WRITE-DETAIL: INITIALIZE TRANSACTION-DETAIL-REPORT: item TRAN-REPORT-AMT is not translated", "0000-TRANFILE-OPEN: OPEN statements are not translated", "0100-REPTFILE-OPEN: OPEN statements are not translated", "0200-CARDXREF-OPEN: OPEN statements are not translated", "0300-TRANTYPE-OPEN: OPEN statements are not translated", "0400-TRANCATG-OPEN: OPEN statements are not translated", "0500-DATEPARM-OPEN: OPEN statements are not translated", "1500-A-LOOKUP-XREF: READ statements are not translated", "1500-B-LOOKUP-TRANTYPE: READ statements are not translated", "1500-C-LOOKUP-TRANCATG: READ statements are not translated", "9000-TRANFILE-CLOSE: CLOSE statements are not translated", "9100-REPTFILE-CLOSE: CLOSE statements are not translated", "9200-CARDXREF-CLOSE: CLOSE statements are not translated", "9300-TRANTYPE-CLOSE: CLOSE statements are not translated", "9400-TRANCATG-CLOSE: CLOSE statements are not translated", "9500-DATEPARM-CLOSE: CLOSE statements are not translated", "9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository", "9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBTRN03C-0059", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').", "app/cbl/CBTRN03C.cbl:170-173", false, "performs 1000-TRANFILE-GET-NEXT, which is not translated", List.of("END-OF-FILE", "END-OF-FILE", "TRAN-PROC-TS", "WS-START-DATE", "END-OF-FILE"), "untranslated (performs 1000-TRANFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBTRN03C-0060", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF TRAN-PROC-TS (1:10) >= WS-START-DATE).", "app/cbl/CBTRN03C.cbl:172-175", false, "performs 1000-TRANFILE-GET-NEXT, which is not translated", List.of("TRAN-PROC-TS", "WS-START-DATE", "TRAN-PROC-TS", "WS-END-DATE", "TRAN-PROC-TS", "WS-START-DATE"), "untranslated (performs 1000-TRANFILE-GET-NEXT, which is not translated)"),
            new RuleInfo("BR-CBTRN03C-0061", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').", "app/cbl/CBTRN03C.cbl:178-181", false, "unexpected 'END-IF' (not a statement)", List.of("END-OF-FILE", "TRAN-RECORD", "WS-CURR-CARD-NUM", "TRAN-CARD-NUM", "END-OF-FILE"), "untranslated (unexpected 'END-IF' (not a statement))"),
            new RuleInfo("BR-CBTRN03C-0062", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-CURR-CARD-NUM NOT= TRAN-CARD-NUM).", "app/cbl/CBTRN03C.cbl:180-183", false, "DISPLAY of group item TRAN-RECORD is not translated", List.of("TRAN-RECORD", "WS-CURR-CARD-NUM", "TRAN-CARD-NUM", "WS-FIRST-TIME", "WS-CURR-CARD-NUM", "TRAN-CARD-NUM"), "untranslated (DISPLAY of group item TRAN-RECORD is not translated)"),
            new RuleInfo("BR-CBTRN03C-0063", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'N').", "app/cbl/CBTRN03C.cbl:181-184", true, null, List.of("WS-CURR-CARD-NUM", "TRAN-CARD-NUM", "WS-FIRST-TIME"), ""),
            new RuleInfo("BR-CBTRN03C-0064", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'Y').", "app/cbl/CBTRN03C.cbl:274-277", true, null, List.of("WS-FIRST-TIME", "REPT-START-DATE", "WS-START-DATE"), ""),
            new RuleInfo("BR-CBTRN03C-0065", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF FUNCTION MOD(WS-LINE-COUNTER, WS-PAGE-SIZE).", "app/cbl/CBTRN03C.cbl:281-284", false, "FUNCTION expressions are not translated", List.of("WS-LINE-COUNTER", "WS-PAGE-SIZE", "WS-LINE-COUNTER", "WS-PAGE-SIZE"), "untranslated (FUNCTION expressions are not translated)"),
            new RuleInfo("BR-CBTRN03C-0066", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF TRANREPT-STATUS = '00').", "app/cbl/CBTRN03C.cbl:345-348", true, null, List.of("FD-REPTFILE-REC", "TRANREPT-STATUS", "APPL-RESULT", "TRANREPT-STATUS"), "translated procedural statement(s) (1 op(s))"));

    @Override public String programId() { return "CBTRN03C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CBTRN03C.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBTRN03C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBTRN03C-0059": rule0(st); return;
            case "BR-CBTRN03C-0060": rule1(st); return;
            case "BR-CBTRN03C-0061": rule2(st); return;
            case "BR-CBTRN03C-0062": rule3(st); return;
            case "BR-CBTRN03C-0063": rule4(st); return;
            case "BR-CBTRN03C-0064": rule5(st); return;
            case "BR-CBTRN03C-0065": rule6(st); return;
            case "BR-CBTRN03C-0066": rule7(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pM0550DateparmRead(st);
            pM1000TranfileGetNext(st);
            pM1100WriteTransactionReport(st);
            pM1110WritePageTotals(st);
            pM1120WriteAccountTotals(st);
            pM1110WriteGrandTotals(st);
            pM1120WriteHeaders(st);
            pM1111WriteReportRec(st);
            pM1120WriteDetail(st);
            pM0000TranfileOpen(st);
            pM0100ReptfileOpen(st);
            pM0200CardxrefOpen(st);
            pM0300TrantypeOpen(st);
            pM0400TrancatgOpen(st);
            pM0500DateparmOpen(st);
            pM1500ALookupXref(st);
            pM1500BLookupTrantype(st);
            pM1500CLookupTrancatg(st);
            pM9000TranfileClose(st);
            pM9100ReptfileClose(st);
            pM9200CardxrefClose(st);
            pM9300TrantypeClose(st);
            pM9400TrancatgClose(st);
            pM9500DateparmClose(st);
            pM9999AbendProgram(st);
            pM9910DisplayIoStatus(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        throw new NotTranslatedException("MAIN-ENTRY: NEXT SENTENCE is not translated");
    }

    /** Paragraph 0550-DATEPARM-READ. */
    void pM0550DateparmRead(CobolState st) {
        throw new NotTranslatedException("0550-DATEPARM-READ: READ statements are not translated");
    }

    /** Paragraph 1000-TRANFILE-GET-NEXT. */
    void pM1000TranfileGetNext(CobolState st) {
        throw new NotTranslatedException("1000-TRANFILE-GET-NEXT: READ statements are not translated");
    }

    /** Paragraph 1100-WRITE-TRANSACTION-REPORT. */
    void pM1100WriteTransactionReport(CobolState st) {
        throw new NotTranslatedException("1100-WRITE-TRANSACTION-REPORT: FUNCTION expressions are not translated");
    }

    /** Paragraph 1110-WRITE-PAGE-TOTALS. */
    void pM1110WritePageTotals(CobolState st) {
        st.move("REPT-PAGE-TOTAL", st.val("WS-PAGE-TOTAL"));
        st.move("FD-REPTFILE-REC", st.val("REPORT-PAGE-TOTALS"));
        pM1111WriteReportRec(st);
        st.setNum("WS-GRAND-TOTAL", st.num("WS-GRAND-TOTAL").add(st.num("WS-PAGE-TOTAL")), false);
        st.move("WS-PAGE-TOTAL", new BigDecimal("0"));
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        st.move("FD-REPTFILE-REC", st.val("TRANSACTION-HEADER-2"));
        pM1111WriteReportRec(st);
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        // EXIT
    }

    /** Paragraph 1120-WRITE-ACCOUNT-TOTALS. */
    void pM1120WriteAccountTotals(CobolState st) {
        st.move("REPT-ACCOUNT-TOTAL", st.val("WS-ACCOUNT-TOTAL"));
        st.move("FD-REPTFILE-REC", st.val("REPORT-ACCOUNT-TOTALS"));
        pM1111WriteReportRec(st);
        st.move("WS-ACCOUNT-TOTAL", new BigDecimal("0"));
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        st.move("FD-REPTFILE-REC", st.val("TRANSACTION-HEADER-2"));
        pM1111WriteReportRec(st);
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        // EXIT
    }

    /** Paragraph 1110-WRITE-GRAND-TOTALS. */
    void pM1110WriteGrandTotals(CobolState st) {
        st.move("REPT-GRAND-TOTAL", st.val("WS-GRAND-TOTAL"));
        st.move("FD-REPTFILE-REC", st.val("REPORT-GRAND-TOTALS"));
        pM1111WriteReportRec(st);
        // EXIT
    }

    /** Paragraph 1120-WRITE-HEADERS. */
    void pM1120WriteHeaders(CobolState st) {
        st.move("FD-REPTFILE-REC", st.val("REPORT-NAME-HEADER"));
        pM1111WriteReportRec(st);
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        st.move("FD-REPTFILE-REC", st.val("WS-BLANK-LINE"));
        pM1111WriteReportRec(st);
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        st.move("FD-REPTFILE-REC", st.val("TRANSACTION-HEADER-1"));
        pM1111WriteReportRec(st);
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        st.move("FD-REPTFILE-REC", st.val("TRANSACTION-HEADER-2"));
        pM1111WriteReportRec(st);
        st.setNum("WS-LINE-COUNTER", st.num("WS-LINE-COUNTER").add(new BigDecimal("1")), false);
        // EXIT
    }

    /** Paragraph 1111-WRITE-REPORT-REC. */
    void pM1111WriteReportRec(CobolState st) {
        throw new NotTranslatedException("1111-WRITE-REPORT-REC: WRITE statements are not translated");
    }

    /** Paragraph 1120-WRITE-DETAIL. */
    void pM1120WriteDetail(CobolState st) {
        throw new NotTranslatedException("1120-WRITE-DETAIL: INITIALIZE TRANSACTION-DETAIL-REPORT: item TRAN-REPORT-AMT is not translated");
    }

    /** Paragraph 0000-TRANFILE-OPEN. */
    void pM0000TranfileOpen(CobolState st) {
        throw new NotTranslatedException("0000-TRANFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0100-REPTFILE-OPEN. */
    void pM0100ReptfileOpen(CobolState st) {
        throw new NotTranslatedException("0100-REPTFILE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0200-CARDXREF-OPEN. */
    void pM0200CardxrefOpen(CobolState st) {
        throw new NotTranslatedException("0200-CARDXREF-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0300-TRANTYPE-OPEN. */
    void pM0300TrantypeOpen(CobolState st) {
        throw new NotTranslatedException("0300-TRANTYPE-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0400-TRANCATG-OPEN. */
    void pM0400TrancatgOpen(CobolState st) {
        throw new NotTranslatedException("0400-TRANCATG-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 0500-DATEPARM-OPEN. */
    void pM0500DateparmOpen(CobolState st) {
        throw new NotTranslatedException("0500-DATEPARM-OPEN: OPEN statements are not translated");
    }

    /** Paragraph 1500-A-LOOKUP-XREF. */
    void pM1500ALookupXref(CobolState st) {
        throw new NotTranslatedException("1500-A-LOOKUP-XREF: READ statements are not translated");
    }

    /** Paragraph 1500-B-LOOKUP-TRANTYPE. */
    void pM1500BLookupTrantype(CobolState st) {
        throw new NotTranslatedException("1500-B-LOOKUP-TRANTYPE: READ statements are not translated");
    }

    /** Paragraph 1500-C-LOOKUP-TRANCATG. */
    void pM1500CLookupTrancatg(CobolState st) {
        throw new NotTranslatedException("1500-C-LOOKUP-TRANCATG: READ statements are not translated");
    }

    /** Paragraph 9000-TRANFILE-CLOSE. */
    void pM9000TranfileClose(CobolState st) {
        throw new NotTranslatedException("9000-TRANFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9100-REPTFILE-CLOSE. */
    void pM9100ReptfileClose(CobolState st) {
        throw new NotTranslatedException("9100-REPTFILE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9200-CARDXREF-CLOSE. */
    void pM9200CardxrefClose(CobolState st) {
        throw new NotTranslatedException("9200-CARDXREF-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9300-TRANTYPE-CLOSE. */
    void pM9300TrantypeClose(CobolState st) {
        throw new NotTranslatedException("9300-TRANTYPE-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9400-TRANCATG-CLOSE. */
    void pM9400TrancatgClose(CobolState st) {
        throw new NotTranslatedException("9400-TRANCATG-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9500-DATEPARM-CLOSE. */
    void pM9500DateparmClose(CobolState st) {
        throw new NotTranslatedException("9500-DATEPARM-CLOSE: CLOSE statements are not translated");
    }

    /** Paragraph 9999-ABEND-PROGRAM. */
    void pM9999AbendProgram(CobolState st) {
        throw new NotTranslatedException("9999-ABEND-PROGRAM: called program CEE3ABD is not in the repository");
    }

    /** Paragraph 9910-DISPLAY-IO-STATUS. */
    void pM9910DisplayIoStatus(CobolState st) {
        throw new NotTranslatedException("9910-DISPLAY-IO-STATUS: DISPLAY of group item IO-STATUS-04 is not translated");
    }

    /**
     * Rule BR-CBTRN03C-0059 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBTRN03C.cbl:170-173
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBTRN03C-0059 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
        // Untranslated reason: performs 1000-TRANFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBTRN03C-0059: performs 1000-TRANFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBTRN03C-0060 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF TRAN-PROC-TS (1:10) >= WS-START-DATE).
     * @citation app/cbl/CBTRN03C.cbl:172-175
     */
    void rule1(CobolState st) {
        // Rule condition: BR-CBTRN03C-0060 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF TRAN-PROC-TS (1:10) >= WS-START-DATE).
        // Untranslated reason: performs 1000-TRANFILE-GET-NEXT, which is not translated
        throw new NotTranslatedException("Rule BR-CBTRN03C-0060: performs 1000-TRANFILE-GET-NEXT, which is not translated");
    }

    /**
     * Rule BR-CBTRN03C-0061 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
     * @citation app/cbl/CBTRN03C.cbl:178-181
     */
    void rule2(CobolState st) {
        // Rule condition: BR-CBTRN03C-0061 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
        // Untranslated reason: unexpected 'END-IF' (not a statement)
        throw new NotTranslatedException("Rule BR-CBTRN03C-0061: unexpected 'END-IF' (not a statement)");
    }

    /**
     * Rule BR-CBTRN03C-0062 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-CURR-CARD-NUM NOT= TRAN-CARD-NUM).
     * @citation app/cbl/CBTRN03C.cbl:180-183
     */
    void rule3(CobolState st) {
        // Rule condition: BR-CBTRN03C-0062 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-CURR-CARD-NUM NOT= TRAN-CARD-NUM).
        // Untranslated reason: DISPLAY of group item TRAN-RECORD is not translated
        throw new NotTranslatedException("Rule BR-CBTRN03C-0062: DISPLAY of group item TRAN-RECORD is not translated");
    }

    /**
     * Rule BR-CBTRN03C-0063 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'N').
     * @citation app/cbl/CBTRN03C.cbl:181-184
     */
    void rule4(CobolState st) {
        if (!(st.cmp(st.str("WS-CURR-CARD-NUM"), st.str("TRAN-CARD-NUM")) == 0)) {
            if ((st.cmp(st.str("WS-FIRST-TIME"), "N") == 0)) {
                pM1120WriteAccountTotals(st);
            }
        }
    }

    /**
     * Rule BR-CBTRN03C-0064 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'Y').
     * @citation app/cbl/CBTRN03C.cbl:274-277
     */
    void rule5(CobolState st) {
        if ((st.cmp(st.str("WS-FIRST-TIME"), "Y") == 0)) {
            st.move("WS-FIRST-TIME", "N");
            st.move("REPT-START-DATE", st.val("WS-START-DATE"));
        }
    }

    /**
     * Rule BR-CBTRN03C-0065 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF FUNCTION MOD(WS-LINE-COUNTER, WS-PAGE-SIZE).
     * @citation app/cbl/CBTRN03C.cbl:281-284
     */
    void rule6(CobolState st) {
        // Rule condition: BR-CBTRN03C-0065 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF FUNCTION MOD(WS-LINE-COUNTER, WS-PAGE-SIZE).
        // Untranslated reason: FUNCTION expressions are not translated
        throw new NotTranslatedException("Rule BR-CBTRN03C-0065: FUNCTION expressions are not translated");
    }

    /**
     * Rule BR-CBTRN03C-0066 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF TRANREPT-STATUS = '00').
     * @citation app/cbl/CBTRN03C.cbl:345-348
     */
    void rule7(CobolState st) {
        st.move("APPL-RESULT", new BigDecimal("0"));
    }
}
