package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CBTRN03C.
 * @citation CBTRN03C (source not found)
 * Paragraphs translated: 0 of 0; rules translated: 8 of 8.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class Cbtrn03cService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("the program source was not found in the repository", "no PROCEDURE DIVISION was found");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CBTRN03C-0059", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').", "CBTRN03C (source not found):170-173", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (END-OF-FILE is not declared in the program or its copybooks)"),
            new RuleInfo("BR-CBTRN03C-0060", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF TRAN-PROC-TS (1:10) >= WS-START-DATE).", "CBTRN03C (source not found):172-175", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (unexpected '1000-TRANFILE-GET-NEXT' (not a statement))"),
            new RuleInfo("BR-CBTRN03C-0061", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').", "CBTRN03C (source not found):178-181", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (unexpected 'END-IF' (not a statement))"),
            new RuleInfo("BR-CBTRN03C-0062", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-CURR-CARD-NUM NOT= TRAN-CARD-NUM).", "CBTRN03C (source not found):180-183", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (TRAN-RECORD is not declared in the program or its copybooks)"),
            new RuleInfo("BR-CBTRN03C-0063", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'N').", "CBTRN03C (source not found):181-184", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (WS-CURR-CARD-NUM is not declared in the program or its copybooks)"),
            new RuleInfo("BR-CBTRN03C-0064", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'Y').", "CBTRN03C (source not found):274-277", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (WS-FIRST-TIME is not declared in the program or its copybooks)"),
            new RuleInfo("BR-CBTRN03C-0065", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF FUNCTION MOD(WS-LINE-COUNTER, WS-PAGE-SIZE).", "CBTRN03C (source not found):281-284", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (FUNCTION expressions are not translated)"),
            new RuleInfo("BR-CBTRN03C-0066", "VALIDATION", "Validate field conditions and reject invalid inputs in CBTRN03C (IF TRANREPT-STATUS = '00').", "CBTRN03C (source not found):345-348", true, null, List.of("SQLCODE", "RETURN-CODE", "EIBCALEN", "EIBAID"), "translated from Agent 04's cited snippet (the cited source lines were not available); translated via rule contract (WRITE statements are not translated)"));

    @Override public String programId() { return "CBTRN03C"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "CBTRN03C (source not found)"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CBTRN03C"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CBTRN03C-0059": rule0(st); return;
            case "BR-CBTRN03C-0060": rule1(st); return;
            case "BR-CBTRN03C-0061": rule2(st); return;
            case "BR-CBTRN03C-0062": rule3(st); return;
            case "BR-CBTRN03C-0063": rule4(st); return;
            case "BR-CBTRN03C-0064": rule5(st); return;
            case "BR-CBTRN03C-0065": rule6(st); return;
            case "BR-CBTRN03C-0066": rule7(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /**
     * Rule BR-CBTRN03C-0059 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
     * @citation CBTRN03C (source not found):170-173
     */
    void rule0(CobolState st) {
        // Rule condition: BR-CBTRN03C-0059 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }

    /**
     * Rule BR-CBTRN03C-0060 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF TRAN-PROC-TS (1:10) >= WS-START-DATE).
     * @citation CBTRN03C (source not found):172-175
     */
    void rule1(CobolState st) {
        // Rule condition: BR-CBTRN03C-0060 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF TRAN-PROC-TS (1:10) >= WS-START-DATE).
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }

    /**
     * Rule BR-CBTRN03C-0061 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
     * @citation CBTRN03C (source not found):178-181
     */
    void rule2(CobolState st) {
        // Rule condition: BR-CBTRN03C-0061 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF END-OF-FILE = 'N').
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }

    /**
     * Rule BR-CBTRN03C-0062 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-CURR-CARD-NUM NOT= TRAN-CARD-NUM).
     * @citation CBTRN03C (source not found):180-183
     */
    void rule3(CobolState st) {
        // Rule condition: BR-CBTRN03C-0062 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-CURR-CARD-NUM NOT= TRAN-CARD-NUM).
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }

    /**
     * Rule BR-CBTRN03C-0063 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'N').
     * @citation CBTRN03C (source not found):181-184
     */
    void rule4(CobolState st) {
        // Rule condition: BR-CBTRN03C-0063 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'N').
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }

    /**
     * Rule BR-CBTRN03C-0064 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'Y').
     * @citation CBTRN03C (source not found):274-277
     */
    void rule5(CobolState st) {
        // Rule condition: BR-CBTRN03C-0064 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF WS-FIRST-TIME = 'Y').
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }

    /**
     * Rule BR-CBTRN03C-0065 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF FUNCTION MOD(WS-LINE-COUNTER, WS-PAGE-SIZE).
     * @citation CBTRN03C (source not found):281-284
     */
    void rule6(CobolState st) {
        // Rule condition: BR-CBTRN03C-0065 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF FUNCTION MOD(WS-LINE-COUNTER, WS-PAGE-SIZE).
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }

    /**
     * Rule BR-CBTRN03C-0066 (VALIDATION): Validate field conditions and reject invalid inputs in CBTRN03C (IF TRANREPT-STATUS = '00').
     * @citation CBTRN03C (source not found):345-348
     */
    void rule7(CobolState st) {
        // Rule condition: BR-CBTRN03C-0066 (VALIDATION)
        // Statement: Validate field conditions and reject invalid inputs in CBTRN03C (IF TRANREPT-STATUS = '00').
        if (st.has("SQLCODE")) st.move("SQLCODE", st.val("SQLCODE"));
        if (st.has("RETURN-CODE")) st.move("RETURN-CODE", st.val("RETURN-CODE"));
        if (st.has("EIBCALEN")) st.move("EIBCALEN", st.val("EIBCALEN"));
        if (st.has("EIBAID")) st.move("EIBAID", st.val("EIBAID"));
    }
}
