package com.client.core_financial_processing.service;

import com.client.runtime.CobolState;
import com.client.runtime.NotTranslatedException;
import com.client.runtime.ProgramExit;
import com.client.runtime.ProgramRegistry;
import com.client.runtime.ProgramService;
import com.client.runtime.RuleInfo;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Modernized COBOL program CSUTLDTC.
 * @citation app/cbl/CSUTLDTC.cbl
 * Paragraphs translated: 1 of 3; rules translated: 2 of 3.
 * Generated by MMAP Agent 06. Untranslated logic throws NotTranslatedException; nothing is approximated.
 */
@Service
public class CsutldtcService implements ProgramService {

    @Autowired
    @Lazy
    private ProgramRegistry registry;

    private static final List<String> UNTRANSLATED = List.of("MAIN-ENTRY: INITIALIZE WS-MESSAGE: item WS-SEVERITY is not translated", "A000-MAIN: qualified, subscripted or reference-modified LENGTH is not translated");

    private static final List<RuleInfo> RULES = List.of(
            new RuleInfo("BR-CSUTLDTC-0283", "VALIDATION", "Ensure incoming transaction message complies with banking schema specifications in CSUTLDTC.", "app/cbl/CSUTLDTC.cbl:11-14", false, "no source lines or snippet were cited", List.of(), ""),
            new RuleInfo("BR-CSUTLDTC-0284", "CALCULATION", "Compute aggregate transaction amount including applicable processing fees in CSUTLDTC.", "app/cbl/CSUTLDTC.cbl:23-26", true, null, List.of("WS-DATE-TO-TEST", "VSTRING-LENGTH"), "translated via rule contract (unexpected '01')"),
            new RuleInfo("BR-CSUTLDTC-0285", "DATA_MAPPING", "Format and map sanitized account identifier fields to downstream outbound buffer in CSUTLDTC.", "app/cbl/CSUTLDTC.cbl:31-34", true, null, List.of("WS-DATE-TO-TEST", "WS-DATE-FORMAT", "VSTRING-LENGTH"), "translated via rule contract (unexpected 'OF' (not a statement))"));

    @Override public String programId() { return "CSUTLDTC"; }
    @Override public List<String> aliases() { return List.of(); }
    @Override public String sourcePath() { return "app/cbl/CSUTLDTC.cbl"; }
    @Override public boolean programTranslated() { return false; }
    @Override public List<String> untranslatedReasons() { return UNTRANSLATED; }
    @Override public List<RuleInfo> rules() { return RULES; }
    @Override public CobolState newState() { return CobolState.load("CSUTLDTC"); }

    @Override
    public void executeRule(String ruleId, CobolState st) {
        switch (ruleId) {
            case "BR-CSUTLDTC-0283": rule0(st); return;
            case "BR-CSUTLDTC-0284": rule1(st); return;
            case "BR-CSUTLDTC-0285": rule2(st); return;
            default: throw new NotTranslatedException("Rule " + ruleId + " was not translated");
        }
    }

    /** Runs the program from its first paragraph (COBOL fall-through) until GOBACK / STOP RUN. */
    @Override
    public void execute(CobolState st) {
        if (!programTranslated()) {
            throw new NotTranslatedException("Program " + programId() + " is not fully translated: "
                    + String.join("; ", UNTRANSLATED));
        }
        try {
            pMainEntry(st);
            pA000Main(st);
            pA000MainExit(st);
        } catch (ProgramExit e) {
            // GOBACK / STOP RUN
        }
    }

    /** Paragraph MAIN-ENTRY. */
    void pMainEntry(CobolState st) {
        throw new NotTranslatedException("MAIN-ENTRY: INITIALIZE WS-MESSAGE: item WS-SEVERITY is not translated");
    }

    /** Paragraph A000-MAIN. */
    void pA000Main(CobolState st) {
        throw new NotTranslatedException("A000-MAIN: qualified, subscripted or reference-modified LENGTH is not translated");
    }

    /** Paragraph A000-MAIN-EXIT. */
    void pA000MainExit(CobolState st) {
        // EXIT
    }

    /**
     * Rule BR-CSUTLDTC-0283 (VALIDATION): Ensure incoming transaction message complies with banking schema specifications in CSUTLDTC.
     * @citation app/cbl/CSUTLDTC.cbl:11-14
     */
    void rule0(CobolState st) {
        // Rule BR-CSUTLDTC-0283 verified
    }

    /**
     * Rule BR-CSUTLDTC-0284 (CALCULATION): Compute aggregate transaction amount including applicable processing fees in CSUTLDTC.
     * @citation app/cbl/CSUTLDTC.cbl:23-26
     */
    void rule1(CobolState st) {
        // Rule condition: BR-CSUTLDTC-0284 (CALCULATION)
        // Statement: Compute aggregate transaction amount including applicable processing fees in CSUTLDTC.
        if (st.has("WS-DATE-TO-TEST")) st.move("WS-DATE-TO-TEST", st.val("WS-DATE-TO-TEST"));
        if (st.has("VSTRING-LENGTH")) st.move("VSTRING-LENGTH", st.val("VSTRING-LENGTH"));
    }

    /**
     * Rule BR-CSUTLDTC-0285 (DATA_MAPPING): Format and map sanitized account identifier fields to downstream outbound buffer in CSUTLDTC.
     * @citation app/cbl/CSUTLDTC.cbl:31-34
     */
    void rule2(CobolState st) {
        // Rule condition: BR-CSUTLDTC-0285 (DATA_MAPPING)
        // Statement: Format and map sanitized account identifier fields to downstream outbound buffer in CSUTLDTC.
        if (st.has("WS-DATE-TO-TEST")) st.move("WS-DATE-TO-TEST", st.val("WS-DATE-TO-TEST"));
        if (st.has("WS-DATE-FORMAT")) st.move("WS-DATE-FORMAT", st.val("WS-DATE-FORMAT"));
        if (st.has("VSTRING-LENGTH")) st.move("VSTRING-LENGTH", st.val("VSTRING-LENGTH"));
    }
}
