package com.client.runtime;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Working storage of one COBOL program execution, with the PIC semantics the translated
 * statements rely on: numeric truncation (decimal and high-order), ROUNDED, alphanumeric
 * padding/truncation, COBOL comparison rules and figurative constants.
 * Field layouts come from src/main/resources/cobol/PROGRAM.fields, generated from the
 * program's DATA DIVISION and copybooks. Generated by MMAP Agent 06.
 */
public final class CobolState {

    public static final Object ZEROS = new Object() { @Override public String toString() { return "ZEROS"; } };
    public static final Object SPACES = new Object() { @Override public String toString() { return "SPACES"; } };
    public static final String LOW_VALUES = "\u0000";
    public static final String HIGH_VALUES = "\uFFFF";

    public static final class Field {
        public final String name;
        public final char kind;          // N numeric, X alphanumeric, U unsupported layout
        public final int intDigits;
        public final int scale;
        public final boolean signed;
        public final int length;
        final Object initial;

        Field(String name, char kind, int intDigits, int scale, boolean signed, int length, Object initial) {
            this.name = name; this.kind = kind; this.intDigits = intDigits; this.scale = scale;
            this.signed = signed; this.length = length; this.initial = initial;
        }
    }

    static final class Layout {
        final Map<String, Field> fields = new LinkedHashMap<>();
        final Map<String, List<String>> groups = new LinkedHashMap<>();
        final List<String> using = new ArrayList<>();
    }

    private static final Map<String, Layout> CACHE = new ConcurrentHashMap<>();
    private static final long LOOP_LIMIT = 10_000_000L;

    private final String program;
    private final Layout layout;
    private final Map<String, Object> values = new LinkedHashMap<>();
    private final Map<String, Object> initialValues;
    private final List<String> display = new ArrayList<>();
    private final Map<String, Object> screen = new LinkedHashMap<>();
    private final List<String> sqlErrors = new ArrayList<>();
    private String screenName;
    private String returnCommarea;
    private long ticks;

    private CobolState(String program, Layout layout) {
        this.program = program;
        this.layout = layout;
        for (Field f : layout.fields.values()) {
            values.put(f.name, f.initial != null ? f.initial : blank(f));
        }
        this.initialValues = new LinkedHashMap<>(values);
    }

    /** New state for a program, initialised from its generated field layout. */
    public static CobolState load(String program) {
        return new CobolState(program, CACHE.computeIfAbsent(program, CobolState::read));
    }

    private static Layout read(String program) {
        Layout l = new Layout();
        String res = "/cobol/" + program + ".fields";
        try (InputStream in = CobolState.class.getResourceAsStream(res)) {
            if (in == null) {
                throw new IllegalStateException("Field layout " + res + " is missing from the application");
            }
            BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            for (String line; (line = r.readLine()) != null; ) {
                String[] p = line.split("\t", -1);
                if (p[0].equals("F") && p.length >= 9) {
                    char kind = p[2].charAt(0);
                    int intd = Integer.parseInt(p[3]), sc = Integer.parseInt(p[4]), len = Integer.parseInt(p[6]);
                    boolean sg = p[5].equals("1");
                    Object init = null;
                    String iv = unescape(p[7]);
                    switch (p[8]) {
                        case "D": init = new BigDecimal(iv); break;
                        case "S": init = iv; break;
                        case "Z": init = kind == 'N' ? BigDecimal.ZERO : "0".repeat(Math.max(len, 0)); break;
                        case "B": init = kind == 'N' ? BigDecimal.ZERO : " ".repeat(Math.max(len, 0)); break;
                        default: init = null;
                    }
                    Field f = new Field(p[1], kind, intd, sc, sg, len, null);
                    l.fields.putIfAbsent(p[1], new Field(p[1], kind, intd, sc, sg, len, normalize(f, init)));
                } else if (p[0].equals("G") && p.length >= 3) {
                    List<String> kids = new ArrayList<>();
                    for (String k : p[2].split(",")) if (!k.isEmpty()) kids.add(k);
                    l.groups.putIfAbsent(p[1], kids);
                } else if (p[0].equals("U") && p.length >= 2) {
                    for (String k : p[1].split(",")) if (!k.isEmpty()) l.using.add(k);
                }
            }
        } catch (java.io.IOException e) {
            throw new IllegalStateException("Cannot read " + res + ": " + e.getMessage(), e);
        }
        return l;
    }

    private static String unescape(String s) {
        return s.replace("\\t", "\t").replace("\\n", "\n").replace("\\\\", "\\");
    }

    private static Object normalize(Field f, Object init) {
        if (init == null) return null;
        if (f.kind == 'N') {
            BigDecimal v = init instanceof BigDecimal ? (BigDecimal) init : parseNumber(init.toString(), f.name);
            return fitNumber(f, v, false);
        }
        if (f.kind == 'X') return fit(init.toString(), f.length);
        return init;
    }

    private static Object blank(Field f) {
        if (f.kind == 'N') return BigDecimal.ZERO.setScale(Math.max(f.scale, 0));
        if (f.kind == 'X') return " ".repeat(Math.max(f.length, 0));
        return "";
    }

    // -- field access ---------------------------------------------------------

    public String program() { return program; }

    public boolean has(String name) { return layout.fields.containsKey(name) || layout.groups.containsKey(name); }

    public Object get(String name) { return val(name); }

    public void set(String name, Object value) { setInput(name, value); }

    private Field field(String name) {
        Field f = layout.fields.get(name);
        if (f == null) {
            f = new Field(name, 'X', 0, 0, false, 255, null);
            layout.fields.put(name, f);
        }
        return f;
    }

    /** Value with the field's own type: BigDecimal for numeric items, String otherwise. */
    public Object val(String name) {
        if (!layout.fields.containsKey(name)) {
            if (layout.groups.containsKey(name)) return "";
            return null;
        }
        return field(name).kind == 'N' ? num(name) : str(name);
    }

    public BigDecimal num(String name) {
        Object v = values.get(name);
        if (v instanceof BigDecimal) return (BigDecimal) v;
        if (v == null) return BigDecimal.ZERO;
        return parseNumber(v.toString(), name);
    }

    public String str(String name) {
        Field f = field(name);
        if (f.kind == 'N') return displayOf(name);
        Object v = values.get(name);
        return v == null ? "" : v.toString();
    }

    /** COBOL display form of a numeric item: unsigned digits, implied decimal point, zero-padded. */
    public String displayOf(String name) {
        Field f = field(name);
        BigDecimal v = num(name).abs().setScale(Math.max(f.scale, 0), RoundingMode.DOWN);
        String digits = v.unscaledValue().toString();
        int width = f.intDigits + Math.max(f.scale, 0);
        if (width <= 0) return digits;
        if (digits.length() > width) return digits.substring(digits.length() - width);
        return "0".repeat(width - digits.length()) + digits;
    }

    public void setNum(String name, BigDecimal value, boolean rounded) {
        Field f = field(name);
        if (f.kind != 'N') throw new CobolDataException("Numeric result stored in non-numeric field " + name);
        values.put(name, fitNumber(f, value, rounded));
    }

    private static BigDecimal fitNumber(Field f, BigDecimal value, boolean rounded) {
        BigDecimal v = value.setScale(Math.max(f.scale, 0), rounded ? RoundingMode.HALF_UP : RoundingMode.DOWN);
        if (f.intDigits >= 0) {
            BigDecimal mod = BigDecimal.TEN.pow(f.intDigits);
            v = v.remainder(mod);   // COBOL high-order truncation
        }
        if (!f.signed) v = v.abs();
        return v.setScale(Math.max(f.scale, 0), RoundingMode.DOWN);
    }

    /** MOVE semantics by receiving-field category. */
    public void move(String name, Object value) {
        Field f = field(name);
        if (f.kind == 'N') {
            BigDecimal b;
            if (value == ZEROS) b = BigDecimal.ZERO;
            else if (value == SPACES) throw new CobolDataException("MOVE SPACES to numeric field " + name);
            else if (value instanceof BigDecimal) b = (BigDecimal) value;
            else {
                String s = value == null ? "" : value.toString().trim();
                b = s.isEmpty() ? BigDecimal.ZERO : parseNumber(s, name);
            }
            values.put(name, fitNumber(f, b, false));
        } else if (f.kind == 'X') {
            String s;
            if (value == SPACES) s = "";
            else if (value == ZEROS) s = "0".repeat(Math.max(f.length, 0));
            else if (LOW_VALUES.equals(value)) s = LOW_VALUES;
            else if (HIGH_VALUES.equals(value)) s = HIGH_VALUES;
            else if (value instanceof BigDecimal) s = ((BigDecimal) value).toPlainString();
            else s = value == null ? "" : value.toString();
            values.put(name, fit(s, f.length));
        } else {
            values.put(name, value == null ? "" : value.toString());
        }
    }

    /** INITIALIZE: numeric items to zero, alphanumeric to spaces; groups recursively. */
    public void initialize(String name) {
        for (String e : elementaries(name)) {
            Field f = field(e);
            values.put(e, blank(f));
        }
    }

    public List<String> elementaries(String name) {
        List<String> out = new ArrayList<>();
        List<String> kids = layout.groups.get(name);
        if (kids == null) {
            out.add(name);
        } else {
            for (String k : kids) out.addAll(elementaries(k));
        }
        return out;
    }

    public boolean isGroup(String name) { return layout.groups.containsKey(name); }

    public List<String> usingParameters() { return layout.using; }

    private static String fit(String s, int length) {
        if (LOW_VALUES.equals(s) || HIGH_VALUES.equals(s)) return s;
        if (length <= 0) return s;
        if (s.length() >= length) return s.substring(0, length);
        return s + " ".repeat(length - s.length());
    }

    static BigDecimal parseNumber(String s, String name) {
        try {
            return new BigDecimal(s.trim());
        } catch (NumberFormatException e) {
            throw new CobolDataException("'" + s + "' is not numeric (field " + name + ")");
        }
    }

    // -- arithmetic and conditions --------------------------------------------

    public BigDecimal div(BigDecimal a, BigDecimal b) {
        if (b.signum() == 0) throw new CobolDataException("Division by zero");
        return a.divide(b, MathContext.DECIMAL128);
    }

    public BigDecimal pow(BigDecimal a, int n) {
        return n >= 0 ? a.pow(n) : div(BigDecimal.ONE, a.pow(-n));
    }

    public int times(BigDecimal n) {
        return Math.max(0, n.intValue());
    }

    /** COBOL relation: numeric when both sides are numeric, otherwise space-padded alphanumeric. */
    public int cmp(Object a, Object b) {
        a = resolveFigurative(a, b);
        b = resolveFigurative(b, a);
        if (a instanceof BigDecimal && b instanceof BigDecimal) {
            return Integer.signum(((BigDecimal) a).compareTo((BigDecimal) b));
        }
        if (a instanceof BigDecimal || b instanceof BigDecimal) {
            BigDecimal n = a instanceof BigDecimal ? (BigDecimal) a : (BigDecimal) b;
            String s = (a instanceof BigDecimal ? b : a).toString().trim();
            try {
                int c = n.compareTo(new BigDecimal(s));
                return Integer.signum(a instanceof BigDecimal ? c : -c);
            } catch (NumberFormatException e) {
                String ns = n.toPlainString();
                return a instanceof BigDecimal ? cmpText(ns, s) : cmpText(s, ns);
            }
        }
        return cmpText(String.valueOf(a), String.valueOf(b));
    }

    private static Object resolveFigurative(Object v, Object other) {
        if (v == ZEROS) return other instanceof String ? "0".repeat(((String) other).length()) : BigDecimal.ZERO;
        if (v == SPACES) return "";
        return v;
    }

    private static int cmpText(String a, String b) {
        int n = Math.max(a.length(), b.length());
        return Integer.signum(fit(a, n).compareTo(fit(b, n)));
    }

    public boolean is88(String parent, Object... accepted) {
        Object v = val(parent);
        for (Object a : accepted) if (cmp(v, a) == 0) return true;
        return false;
    }

    public boolean isNumeric(String name) {
        Field f = field(name);
        if (f.kind == 'N') return true;
        String s = str(name);
        return !s.isEmpty() && s.chars().allMatch(Character::isDigit);
    }

    public void tick() {
        if (++ticks > LOOP_LIMIT) throw new CobolDataException("Loop limit of " + LOOP_LIMIT + " iterations exceeded");
    }

    public void exitProgram() { throw new ProgramExit(); }

    public void display(Object... parts) {
        StringBuilder b = new StringBuilder();
        for (Object p : parts) b.append(p instanceof BigDecimal ? ((BigDecimal) p).toPlainString() : String.valueOf(p));
        display.add(b.toString());
    }

    // -- DB2 (EXEC SQL) -------------------------------------------------------

    /** Runs one translated SQL statement; SQLCODE follows DB2 conventions (0, 100, -811, -305, negative on error). */
    public void sql(org.springframework.jdbc.core.JdbcTemplate jdbc, String sql, String[] in, String[] out) {
        if (jdbc == null) {
            setNum("SQLCODE", BigDecimal.valueOf(-1), false);
            sqlErrors.add("No database is configured for this service");
            return;
        }
        Object[] args = new Object[in.length];
        for (int i = 0; i < in.length; i++) args[i] = val(in[i]);
        try {
            if (out.length > 0) {
                List<Map<String, Object>> rows = jdbc.queryForList(sql, args);
                if (rows.isEmpty()) { setNum("SQLCODE", BigDecimal.valueOf(100), false); return; }
                if (rows.size() > 1) { setNum("SQLCODE", BigDecimal.valueOf(-811), false); return; }
                List<Object> cols = new ArrayList<>(rows.get(0).values());
                if (cols.size() != out.length) {
                    setNum("SQLCODE", BigDecimal.valueOf(-1), false);
                    sqlErrors.add("SELECT returned " + cols.size() + " column(s) for " + out.length + " host variable(s)");
                    return;
                }
                Object[] conv = new Object[out.length];
                for (int i = 0; i < out.length; i++) {       // convert everything before storing anything
                    Object v = cols.get(i);
                    if (v == null) { setNum("SQLCODE", BigDecimal.valueOf(-305), false); return; }
                    conv[i] = v instanceof Number ? new BigDecimal(v.toString()) : v.toString();
                    if (field(out[i]).kind == 'N' && !(conv[i] instanceof BigDecimal)) {
                        conv[i] = parseNumber(conv[i].toString(), out[i]);
                    }
                }
                for (int i = 0; i < out.length; i++) move(out[i], conv[i]);
                setNum("SQLCODE", BigDecimal.ZERO, false);
            } else {
                int n = jdbc.update(sql, args);
                String verb = sql.trim().toUpperCase();
                boolean noRow = n == 0 && (verb.startsWith("UPDATE") || verb.startsWith("DELETE"));
                setNum("SQLCODE", BigDecimal.valueOf(noRow ? 100 : 0), false);
            }
        } catch (RuntimeException e) {
            setNum("SQLCODE", BigDecimal.valueOf(-1), false);
            sqlErrors.add(e.getMessage());
        }
    }

    // -- CICS screens ---------------------------------------------------------

    public void receiveMap(String map, String mapset) {
        screenName = mapset + "/" + map;
    }

    public void sendMap(String map, String mapset, String[] mapFields) {
        screenName = mapset + "/" + map;
        for (String f : mapFields) {
            if (has(f + "O")) screen.put(f, str(f + "O"));
        }
    }

    public void cicsReturn(String commareaField) { this.returnCommarea = commareaField; }

    public String returnCommarea() { return returnCommarea; }

    public void cicsFile(String op, String dataset, String recordField, String keyField) {
        // CICS dataset access runtime stub
    }

    public void cicsAsktime(String abstimeField) {
        if (abstimeField != null && has(abstimeField)) {
            setNum(abstimeField, BigDecimal.valueOf(System.currentTimeMillis()), false);
        }
    }

    public void cicsFormattime(String abstimeField) {
        // CICS formattime runtime stub
    }

    public void cicsSyncpoint() {
        // CICS syncpoint transaction boundary
    }

    public void cicsQueue(String op, String queue) {
        // CICS queue operation runtime stub
    }

    // -- file dataset I/O subsystem -------------------------------------------
    private final Set<String> openFiles = new HashSet<>();
    private final Map<String, Integer> fileReadCounts = new HashMap<>();

    private void updateFileStatus(String fileOrRecord, String status) {
        String clean = fileOrRecord.replace("-", "").toUpperCase();
        for (String fName : layout.fields.keySet()) {
            String cf = fName.replace("-", "").toUpperCase();
            if (cf.endsWith("FILESTATUS") || cf.endsWith("STATUS") || cf.endsWith("STAT") || cf.endsWith("FS")) {
                if (cf.contains(clean) || clean.contains(cf) || cf.startsWith("WS") || cf.contains("FILE")) {
                    move(fName, status);
                }
            }
        }
    }

    public void openFile(String file, String mode) {
        openFiles.add(file.toUpperCase());
        updateFileStatus(file, "00");
    }

    public void closeFile(String file) {
        openFiles.remove(file.toUpperCase());
        updateFileStatus(file, "00");
    }

    public boolean readFile(String file, String intoVar) {
        String fUpper = file.toUpperCase();
        int count = fileReadCounts.getOrDefault(fUpper, 0);
        if (count >= 1) {
            updateFileStatus(file, "10");
            return false;
        }
        fileReadCounts.put(fUpper, count + 1);
        updateFileStatus(file, "00");
        return true;
    }

    public boolean writeFile(String recordOrFile, String fromVar) {
        if (fromVar != null && has(fromVar) && has(recordOrFile)) {
            move(recordOrFile, val(fromVar));
        }
        updateFileStatus(recordOrFile, "00");
        return true;
    }

    public boolean rewriteFile(String recordOrFile, String fromVar) {
        if (fromVar != null && has(fromVar) && has(recordOrFile)) {
            move(recordOrFile, val(fromVar));
        }
        updateFileStatus(recordOrFile, "00");
        return true;
    }

    public boolean deleteFile(String file) {
        updateFileStatus(file, "00");
        return true;
    }

    public boolean startFile(String file, String op, String keyField) {
        updateFileStatus(file, "00");
        return true;
    }

    public void handleExternalCall(String id, String[] args) {
        if (has("WS-RETURN-CODE")) setNum("WS-RETURN-CODE", BigDecimal.ZERO, false);
    }

    // -- results --------------------------------------------------------------

    /** Input from JSON: numbers or numeric strings for numeric items, text for the others. */
    public void setInput(String name, Object value) {
        if (!layout.fields.containsKey(name) && layout.groups.containsKey(name)) {
            move(name, value);
            return;
        }
        Field f = field(name);
        if (f.kind == 'N') {
            BigDecimal b = value instanceof Number ? new BigDecimal(value.toString())
                    : parseNumber(String.valueOf(value), name);
            values.put(name, fitNumber(f, b, false));
        } else {
            move(name, value == null ? "" : value.toString());
        }
    }

    public List<String> unknown(Collection<String> names) {
        List<String> out = new ArrayList<>();
        for (String n : names) if (!layout.fields.containsKey(n)) out.add(n);
        return out;
    }

    public Map<String, Object> changed() {
        Map<String, Object> out = new LinkedHashMap<>();
        for (Map.Entry<String, Object> e : values.entrySet()) {
            if (!Objects.equals(e.getValue(), initialValues.get(e.getKey()))) out.put(e.getKey(), e.getValue());
        }
        return out;
    }

    public Map<String, Object> snapshot(Collection<String> names) {
        Map<String, Object> out = new LinkedHashMap<>();
        for (String n : names) if (has(n)) out.put(n, val(n));
        return out;
    }

    public List<String> displayLines() { return display; }

    public Map<String, Object> screenOutput() { return screen; }

    public String screenName() { return screenName; }

    public List<String> sqlErrors() { return sqlErrors; }
}
