server:
  port: 8080
spring:
  application:
    name: modernized-mainframe-core
  datasource:
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/modernized_db}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 3000
      validation-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
